const{open,read,click,save}=require('./closeout-lib'),assert=require('assert');
const ids=['cargo','engine','hull','magnet','radar','insurance','shield','assist','contract','repair','scanner','buffer','containment','salvage','decoder'];
(async()=>{const q=await open(),p=q.p,rows=[];
async function measure(id){await p.evaluate(()=>{scene15.__start17();const s=scene15.__os,g=scene15.__g13,v=scene15.getVariables();s.x=1000;s.y=300;s.vx=s.vy=0;s.inv=10;g.hazards=[];g.loot.forEach(o=>o.taken=true);v.get('Cargo').setNumber(0);v.get('CargoValue').setNumber(0);});await p.waitForTimeout(120);
await p.evaluate(()=>{const s=scene15.__os;s.x=1000;s.y=300;s.vx=s.vy=0;scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);});await p.waitForTimeout(100);
const visual=await p.evaluate(i=>{const o=scene15.getObjects('Module14')[i];return{visible:!o.isHidden(),frame:o.getAnimationFrame()};},ids.indexOf(id));
if(id==='engine'){await p.keyboard.down('d');await p.waitForTimeout(1800);await p.keyboard.up('d');return{value:await p.evaluate(()=>Math.hypot(scene15.__os.vx,scene15.__os.vy)),visual};}
if(['cargo','magnet','assist','salvage'].includes(id)){await p.evaluate(id=>{const g=scene15.__g13,v=scene15.getVariables(),s=scene15.__os;const o=g.loot.find(o=>o.kind===(id==='salvage'?'energy':'scrap'));o.taken=false;o.x=s.x+(id==='magnet'?36:0);o.y=s.y;window.probeLoot=o;if(id==='cargo')v.get('Cargo').setNumber(8);},id);await p.waitForTimeout(180);return{value:await p.evaluate(id=>id==='cargo'||id==='magnet'?Number(probeLoot.taken):scene15.getVariables().get('CargoValue').getAsNumber(),id),visual};}
if(id==='hull')return{value:(await read(p)).hull,visual};
if(id==='radar'){return{value:await p.evaluate(()=>Number(scene15.getObjects('NavMarker')[0].getString().includes('СЕК ДО БАЗЫ'))),visual};}
if(id==='scanner'){await p.evaluate(()=>{const s=scene15.__os,lane=scene15.__g13.regions.find(r=>r.id==='meteor');s.x=lane.x-700;s.y=lane.y;s.vx=s.vy=0;scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);});await p.waitForTimeout(100);return{value:await p.evaluate(()=>Number(!scene15.getObjects('MeteorTelegraph')[0].isHidden())),visual};}
if(id==='contract'){await p.evaluate(()=>{const v=scene15.getVariables(),s=scene15.__os;v.get('MissionType').setString('scrap');v.get('MissionTarget').setNumber(6);v.get('MissionProgress').setNumber(6);v.get('MissionReward').setNumber(100);v.get('Cargo').setNumber(6);v.get('CargoValue').setNumber(60);s.pass10ContractBoosted=false;s.x=260;s.y=700;s.vx=s.vy=0;scene15.getObjects('Ship')[0].setCenterPositionInScene(260,700);});await p.waitForTimeout(120);return{value:await p.evaluate(()=>scene15.getVariables().get('ContractRewardEarned').getAsNumber()),visual};}
if(id==='repair'){await p.evaluate(()=>scene15.getVariables().get('Hull').setNumber(1));await p.waitForTimeout(100);return{value:(await read(p)).hull,visual};}
if(id==='decoder'){await p.evaluate(()=>{scene15.__g13.secret.cache=true;scene15.__g13.secret.stage=6;});await p.waitForTimeout(120);return{value:(await read(p)).cargoValue,visual};}
if(id==='containment'){await p.evaluate(()=>{const g=scene15.__g13,s=scene15.__os,r=g.regions[0];r.id='radiation';s.x=r.x;s.y=r.y;s.inv=0;scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);g.mission16.radiation=2.49;});await p.waitForTimeout(200);return{value:await p.evaluate(()=>Number(!!scene15.__g13.mission16.isolation)),visual};}
if(id==='buffer'||id==='shield'){await p.evaluate(()=>{const s=scene15.__os,v=scene15.getVariables();s.inv=0;s.pass10Damage=0;s.shieldUsed10=false;v.get('Hull').setNumber(2);v.get('RunDamage').setNumber(1);});await p.waitForTimeout(100);return{value:await p.evaluate(id=>id==='buffer'?scene15.__os.inv:scene15.getVariables().get('Hull').getAsNumber(),id),visual};}
if(id==='insurance'){await p.evaluate(()=>{const s=scene15.__os,v=scene15.getVariables();v.get('CargoValue').setNumber(100);v.get('InsurancePaid').setNumber(0);v.get('Hull').setNumber(0);});await p.waitForTimeout(120);return{value:await p.evaluate(()=>scene15.getVariables().get('InsurancePaid').getAsNumber()),visual};}
}
try{for(const id of ids){const row={module:id,level:1};rows.push(row);try{row.measuredBefore=await measure(id);await p.evaluate(id=>{const v=scene15.getVariables();v.get('GameState').setString('upgrades');v.get('Credits').setNumber(5000);v.get('TechParts').setNumber(20);v.get('Offer1').setString(id);v.get('OffersReady').setNumber(1);},id);await p.waitForTimeout(180);row.price=await p.evaluate(id=>scene15.__osMap.prices[id],id);await click(p,'UpgradeButtonBg');assert(await p.evaluate(id=>scene15.__osModuleDone(id),id));row.measuredAfter=await measure(id);
await p.reload();await p.waitForFunction(()=>window.__osQAState?.state==='menu');assert(await p.evaluate(id=>scene15.__osModuleDone(id),id));row.reloadEffect=await measure(id);
await p.evaluate(()=>{const v=scene15.getVariables();v.get('GameState').setString('upgrades');v.get('TechParts').setNumber(20);});await p.waitForTimeout(150);const before=(await read(p)).credits;await click(p,'ResetButtonBg');await click(p,'ResetConfirmOkBg');row.refund=(await read(p)).credits-before;assert.equal(row.refund,Math.floor(row.price*.75));row.resetEffect=await measure(id);const b=row.measuredBefore.value,a=row.measuredAfter.value,l=row.reloadEffect.value,z=row.resetEffect.value;row.expectedEffect={cargo:'capacity permits ninth item',engine:'+10% thrust/speed',hull:'3 to 4 health',magnet:'pickup at 36 units',radar:'station ETA',insurance:'25% cargo recovery',shield:'absorb first damage',assist:'+3 per collected slot',contract:'+20% contract payout',repair:'critical hull +1 once',scanner:'early meteor warning',buffer:'1.1 seconds invulnerability',containment:'first radiation strike absorbed',salvage:'+20% energy value',decoder:'+60 secret cache'}[id];
const close=(x,y)=>Math.abs(x-y)<(id==='engine'?12:id==='buffer'?.15:.001);row.pass=a>b&&close(a,l)&&close(b,z)&&row.measuredAfter.visual.visible&&row.reloadEffect.visual.visible&&!row.resetEffect.visual.visible;assert(row.pass,'effect or visual mismatch');
}catch(e){row.failure=e.message;row.pass=false;console.log(row);break;}console.log(id,'PASS');}
}finally{save('modules',{mode:'isolated input-state fixtures invoke actual production frame/purchase/save/reset handlers; no module-level writes',rows,errors:q.errors,pass:rows.length===15&&rows.every(x=>x.pass)});await q.browser.close();}})();
