const{open,read,click,go,save}=require('./closeout-lib'),assert=require('assert');
(async()=>{const engine=process.argv[2]||'chromium';process.env.YANDEX_QA_BROWSER=engine;const r={engine,checks:[]};let q;
try{q=await open();const p=q.p;r.version=q.browser.version();assert.equal(await p.locator('#shell17 h1').first().textContent(),'Космический сборщик');r.checks.push('exact rendered title');await click(p,'ButtonBg');
 for(let i=0;i<6;i++){const s=await read(p),loot=s.loot.filter(o=>!o.taken&&o.kind==='scrap').sort((a,b)=>Math.hypot(a.x-s.shipX,a.y-s.shipY)-Math.hypot(b.x-s.shipX,b.y-s.shipY))[0];await go(p,loot.x,loot.y);}
 assert((await read(p)).missionProgress>=6);await p.keyboard.press('Escape');await p.waitForTimeout(200);const t=(await read(p)).runTime;await p.waitForTimeout(500);assert.equal((await read(p)).runTime,t);await p.getByRole('button',{name:'ПРОДОЛЖИТЬ',exact:true}).click();await p.keyboard.press('j');await p.waitForTimeout(150);assert.equal((await read(p)).state,'journal17');await p.getByRole('button',{name:'ПРОДОЛЖИТЬ',exact:true}).click();await go(p,260,700,80);assert.equal((await read(p)).state,'result');await click(p,'ResultButtonBg');assert.equal((await read(p)).state,'upgrades');
 // Earn the upgrade normally: second contract, not a credits fixture.
 await click(p,'UpgradeBackButtonBg');await p.waitForTimeout(250);let s=await read(p);const heavy=s.loot.filter(o=>!o.taken&&o.kind==='heavy').sort((a,b)=>Math.hypot(a.x-s.shipX,a.y-s.shipY)-Math.hypot(b.x-s.shipX,b.y-s.shipY))[0];await go(p,heavy.x,heavy.y);await go(p,260,700,80);assert.equal((await read(p)).state,'result');await click(p,'ResultButtonBg');s=await read(p);const ix=s.offers.findIndex(id=>s.prices[id]<=s.credits);assert(ix>=0);const module=s.offers[ix];await click(p,'UpgradeButtonBg',ix);assert(await p.evaluate(id=>scene15.__osModuleDone(id),module));const credits=(await read(p)).credits;
 await p.reload();await p.waitForFunction(()=>window.__osQAState?.state==='menu');assert.equal((await read(p)).credits,credits);assert(await p.evaluate(id=>scene15.__osModuleDone(id),module));r.purchase={module,creditsAfterReload:credits};await p.getByRole('button',{name:'ВЫБОР СЕКТОРА',exact:true}).click();await p.waitForTimeout(150);assert.equal((await read(p)).state,'sectorSelect');await click(p,'SectorSelectButtonBg',0);
 // Separate collision placement fixture, never writes HP. Natural death has its own test.
 for(let i=0;i<40&&(await read(p)).state==='play';i++){await p.evaluate(()=>{const h=scene15.__g13.hazards[0],s=scene15.__os;s.x=h.x;s.y=h.y;s.vx=s.vy=0;scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);});await p.waitForTimeout(220);}assert.equal((await read(p)).state,'fail');await click(p,'ResultButtonBg');assert.equal((await read(p)).state,'play');r.checks.push('movement/HUD/loot/2 completed contracts','pause/resume/journal','station/result/earned upgrade purchase/sector select','credits and module survive reload','collision death/new flight (placement fixture)');r.pass=true;
}catch(e){r.failure=e.stack;r.pass=false;if(!q)r.environment='ENVIRONMENT NOT AVAILABLE';}finally{if(q){r.errors=q.errors;r.consoleErrors=q.consoleErrors;r.failed=q.failed.filter(x=>!x.url.includes('kaspersky-labs.com'));r.critical=q.external.filter(x=>/^4|^5/.test(x)&&!x.includes('kaspersky-labs.com'));if(r.errors.length||r.consoleErrors.length||r.failed.length||r.critical.length)r.pass=false;await q.browser.close();}save('cross-'+engine,r);console.log(r);}})();
