const {fs,path,root,launch,state,click,steer,sleep}=require('./smart08-play'),assert=require('assert/strict'),cp=require('child_process');
const out=path.join(root,'screenshots','GameplayOverhaul13'),report={pass:'Gameplay Overhaul 13',natural:{events:[]},seeds:[],checks:{},errors:[],screenshots:[]},url='http://127.0.0.1:4230/index.html?dev=1';
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const shot=async(p,n)=>{await p.screenshot({path:path.join(out,n)});report.screenshots.push(n);};
async function attach(p){await p.evaluate(()=>{if(window.__g13Hook)return;window.__g13Hook=true;const proto=gdjs.RuntimeScene.prototype,old=proto.renderAndStep;proto.renderAndStep=function(...a){window.__g13Scene=this;return old.apply(this,a);};});await p.waitForFunction(()=>window.__g13Scene&&window.__osQAState);}
async function objClick(p,n,i=0){const q=await p.evaluate(([n,i])=>{const o=window.__g13Scene.getObjects(n)[i];return{x:o.getX()+o.getWidth()/2,y:o.getY()+o.getHeight()/2};},[n,i]);return click(p,q.x,q.y);}
const event=(name,s)=>report.natural.events.push({name,seconds:+((Date.now()-s)/1000).toFixed(1)});
async function gdata(p){return p.evaluate(()=>{const g=window.__g13Scene.__g13;return{seed:g.seed,regions:g.regions.map(r=>({id:r.id,x:r.x,y:r.y})),loot:g.loot.map(l=>({...l})),signal:g.signal,key:g.key,gate:g.gate,secret:{...g.secret}};});}
async function collectKind(p,kind,count){for(let n=0;n<count;n++){const d=await gdata(p),st=await state(p),q=d.loot.filter(x=>x.kind===kind&&!x.taken).sort((a,b)=>Math.hypot(a.x-st.shipX,a.y-st.shipY)-Math.hypot(b.x-st.shipX,b.y-st.shipY))[0];if(!q)throw new Error('No '+kind);await steer(p,q.x,q.y,70);}}
async function safeRoute(p,target){const st=await state(p),lane=target.y>1700?1900:1650;await steer(p,st.shipX,lane,85);await steer(p,target.x,lane,85);return steer(p,target.x,target.y,60);}
async function buyAffordable(p){const st=await state(p),prices=await p.evaluate(()=>window.__g13Scene.__osMap.prices),choices=st.offers.map((id,i)=>({id,i,cost:prices[id]||999})).filter(x=>x.cost<=st.credits).sort((a,b)=>a.cost-b.cost);if(choices[0]){await objClick(p,'UpgradeButtonBg',choices[0].i);return choices[0].id;}return null;}
async function natural(){const sess=await launch(url,{width:1920,height:1080}),{p,browser,errors}=sess,start=Date.now();try{await attach(p);await objClick(p,'ButtonBg');event('newGame',start);
  await collectKind(p,'scrap',6);event('contract1Loot',start);await steer(p,260,700,105);console.log('after return1 steer',await state(p));await p.waitForFunction(()=>window.__osQAState.state==='result');event('return1',start);await objClick(p,'ResultButtonBg',0);if(await buyAffordable(p))event('upgrade1',start);await objClick(p,'UpgradeBackButtonBg');
  for(let cycle=0;cycle<8&&(await state(p)).contractsCompleted<4;cycle++){const before=await state(p),type=before.missionType;if(type==='container'){const d=await gdata(p),q=d.loot.find(x=>x.kind==='heavy'&&!x.taken);await safeRoute(p,q);}else if(type==='valuable'){await collectKind(p,'energy',2);}else if(type==='nodamage'){await collectKind(p,'scrap',4);}else await collectKind(p,'scrap',Math.min(6,before.missionTarget));await steer(p,260,700,105);await p.waitForFunction(()=>window.__osQAState.state==='result');const after=await state(p);event('return'+(cycle+2),start);if(after.contractsCompleted>=4){await objClick(p,'ResultButtonBg',1);break;}await objClick(p,'ResultButtonBg',0);if(await buyAffordable(p))event('upgrade'+(cycle+2),start);await objClick(p,'UpgradeBackButtonBg');}
  let st=await state(p);console.log('pre-sector2',st);assert.equal(st.state,'sectorSelect','natural progression did not unlock Sector 2');await objClick(p,'SectorSelectButtonBg',1);event('sector2',start);
  const d=await gdata(p);await safeRoute(p,d.signal);event('signal',start);await safeRoute(p,d.key);event('key',start);await safeRoute(p,d.gate);await sleep(p,1800);await steer(p,d.gate.x,d.gate.y,80);await p.waitForFunction(()=>window.__osQAState.secretStage>=4);event('secretEntry',start);
  const routes=[[[5160,2510],[5380,2260],[5560,2620],[5750,2310],[5920,2700],[6060,2460]],[[5180,2240],[5360,2620],[5540,2320],[5720,2700],[5900,2380],[6070,2520]],[[5140,2550],[5320,2300],[5500,2650],[5700,2350],[5890,2690],[6060,2460]],[[5160,2260],[5340,2580],[5530,2260],[5710,2600],[5900,2320],[6070,2500]],[[5140,2480],[5320,2200],[5500,2580],[5680,2250],[5880,2640],[6060,2460]]],variant=(await state(p)).secretTemplate;for(const q of routes[variant]){await sleep(p,700);await steer(p,q[0],q[1],75);}await steer(p,6130,2480,75);event('cache',start);assert.notEqual((await state(p)).state,'fail','natural secret route destroyed the ship');await sleep(p,1800);await safeRoute(p,{x:260,y:700});await p.waitForFunction(()=>window.__osQAState.state==='result');event('finalReturn',start);report.natural.final=await state(p);report.natural.seconds=+((Date.now()-start)/1000).toFixed(1);report.errors.push(...errors);
 }finally{await browser.close();}}
async function capture(){const seed={SectorUnlocked:1,CurrentSector:1,ContractsCompleted:5,Credits:540,TechParts:2,CargoMax:10,HullMax:4,Hull:4,EngineLevel:1,MagnetLevel:1,RadarLevel:1,ShieldLevel:1,RepairLevel:1,ScannerLevel:1,AssistLevel:1,OfferSeed:3,OffersReady:0,RunCount:7};const sess=await launch(url,{width:1920,height:1080},false,seed),{p,browser,errors}=sess;try{await attach(p);await shot(p,'01-menu.png');await objClick(p,'ButtonBg');await shot(p,'02-sector1-spawn.png');let d=await gdata(p);report.seeds.push(d.seed);
  const by=id=>d.regions.find(r=>r.id===id)||d.regions[1];for(const [id,name] of [['working','03-region-working-orbit.png'],['debris','04-region-debris-field.png'],['graveyard','08-poi-wreck.png']]){const r=by(id);await steer(p,r.x,r.y,90);await shot(p,name);}
  await p.keyboard.press('F11');await sleep(p,600);await shot(p,'05-meteor-warning.png');await sleep(p,1300);await shot(p,'06-meteor-flight.png');const val=d.regions.find(r=>r.id==='value')||d.regions[3];await steer(p,val.x,val.y,90);await shot(p,'07-multi-loot-choice.png');await shot(p,'09-mission-event.png');
  await p.evaluate(()=>window.__g13Scene.getVariables().get('GameState').setString('sectorSelect'));await sleep(p,120);await objClick(p,'SectorSelectButtonBg',1);await shot(p,'10-sector2.png');d=await gdata(p);await steer(p,d.signal.x,d.signal.y,120);await shot(p,'11-secret-signal.png');await steer(p,d.key.x,d.key.y,70);await shot(p,'12-access-key-encounter.png');await steer(p,d.gate.x,d.gate.y,145);await shot(p,'13-gate-locked.png');await steer(p,d.gate.x,d.gate.y,120);await sleep(p,650);await shot(p,'14-gate-opening.png');await sleep(p,1100);await steer(p,d.gate.x,d.gate.y,75);await p.waitForFunction(()=>window.__osQAState.secretStage>=4);await shot(p,'15-secret-layout-start.png');
  const routes=[[[5160,2510],[5380,2260],[5560,2620],[5750,2310],[5920,2700],[6060,2460]],[[5180,2240],[5360,2620],[5540,2320],[5720,2700],[5900,2380],[6070,2520]],[[5140,2550],[5320,2300],[5500,2650],[5700,2350],[5890,2690],[6060,2460]],[[5160,2260],[5340,2580],[5530,2260],[5710,2600],[5900,2320],[6070,2500]],[[5140,2480],[5320,2200],[5500,2580],[5680,2250],[5880,2640],[6060,2460]]],variant=(await state(p)).secretTemplate;for(let i=0;i<routes[variant].length;i++){const q=routes[variant][i];await steer(p,q[0],q[1],75);if(i===0)await shot(p,'16-secret-laser-pattern1.png');if(i===2)await shot(p,'17-secret-laser-pattern2.png');if(i===3)await shot(p,'18-secret-debris-maze.png');if(i===5)await shot(p,'19-secret-final-challenge.png');}await shot(p,'20-secret-cache.png');await steer(p,6130,2480,75);await shot(p,'21-upgraded-ship.png');await p.evaluate(()=>window.__g13Scene.getVariables().get('GameState').setString('result'));await sleep(p,120);await shot(p,'22-result.png');await p.evaluate(()=>window.__g13Scene.getVariables().get('GameState').setString('upgrades'));await sleep(p,100);await shot(p,'23-upgrades.png');await p.evaluate(()=>window.__g13Scene.getVariables().get('GameState').setString('play'));await p.keyboard.press('F3');await sleep(p,100);await shot(p,'26-dev-procedural-seed.png');for(let i=0;i<4;i++){await p.keyboard.press('F10');await sleep(p,80);report.seeds.push((await state(p)).seed);}report.errors.push(...errors);
 }finally{await browser.close();}
 const mob=await launch(url,{width:1280,height:720},true);try{await attach(mob.p);await objClick(mob.p,'ButtonBg');await mob.p.touchscreen.tap(980,430);await sleep(mob.p,250);await shot(mob.p,'24-mobile-landscape.png');report.errors.push(...mob.errors);}finally{await mob.browser.close();}
 const por=await launch(url,{width:720,height:1280},true);try{await attach(por.p);assert.equal((await state(por.p)).state,'rotate');await shot(por.p,'25-mobile-portrait.png');report.errors.push(...por.errors);}finally{await por.browser.close();}}
(async()=>{await natural();await capture();report.checks.audit=JSON.parse(cp.execFileSync(process.execPath,['scripts/audit-project.js'],{cwd:root,encoding:'utf8'}));report.checks.runtimeErrors=report.errors;fs.writeFileSync(path.join(root,'docs','gameplay-overhaul13-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.errors.length)process.exitCode=2;})().catch(e=>{console.error(e.stack);process.exit(1);});
