// Layout fixtures are explicit; this is not a natural progression run.
const fs=require('fs'),path=require('path'),assert=require('assert');
const{chromium}=require('C:/Users/Станислав/Documents/ChatGPT/Yandex Games/node_modules/playwright-core');
const executablePath=fs.readdirSync(process.env.LOCALAPPDATA+'/ms-playwright').filter(x=>/^chromium-\d+$/.test(x)).sort((a,b)=>Number(b.split('-')[1])-Number(a.split('-')[1])).map(x=>process.env.LOCALAPPDATA+'/ms-playwright/'+x+'/chrome-win64/chrome.exe').find(x=>fs.existsSync(x));
const folder='screenshots/MobileUI21';fs.mkdirSync(folder,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath}),c=await browser.newContext({viewport:{width:640,height:360},hasTouch:true,isMobile:true,deviceScaleFactor:2}),p=await c.newPage(),r={mode:'mobile browser layout fixtures; real device not available',checks:[],screenshots:[],errors:[]};p.on('pageerror',e=>r.errors.push(e.message));
const shot=async name=>{await p.screenshot({path:folder+'/'+name+'.png'});r.screenshots.push(name);};
const state=async s=>{await p.evaluate(s=>scene21.getVariables().get('GameState').setString(s),s);await p.waitForTimeout(220);};
const audit=async()=>p.evaluate(()=>{const m=scene21.__mobile21,rect=e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y,w:b.width,h:b.height,right:b.right,bottom:b.bottom};};return{viewport:{w:m.width,h:m.height},hud:rect(m.hud),nav:rect(scene21.__ui17.nav),toolbar:rect(scene21.__ui17.toolbar),card:[...document.querySelectorAll('#shell17 .card')].filter(e=>e.getBoundingClientRect().height).map(rect),body:[...document.querySelectorAll('.body21')].filter(e=>e.clientHeight).map(e=>({height:e.clientHeight,scroll:e.scrollHeight})),active:m.active};});
try{
 await p.goto('http://192.168.10.15:4238/');await p.waitForFunction(()=>window.__osQAState?.state==='menu');await p.evaluate(()=>{const f=gdjs.RuntimeScene.prototype.renderAndStep;gdjs.RuntimeScene.prototype.renderAndStep=function(...a){window.scene21=this;return f.apply(this,a);};});await p.waitForFunction(()=>window.scene21?.__ui17);await shot('01-menu-640x360');
 await p.getByRole('button',{name:'НАЧАТЬ ВЫЛЕТ',exact:true}).click();await p.waitForFunction(()=>__osQAState.state==='play');await p.waitForTimeout(300);await shot('02-flight-640x360');r.initial=await audit();assert(r.initial.hud.h<=64);assert(r.initial.nav.bottom<=r.initial.viewport.h);assert(r.initial.nav.right<r.initial.toolbar.x);
 await p.getByRole('button',{name:'ЖУРНАЛ',exact:true}).click();await p.waitForFunction(()=>__osQAState.state==='journal17');await shot('03-journal-640x360');
 await p.getByRole('button',{name:'ПРОДОЛЖИТЬ',exact:true}).click();await p.getByRole('button',{name:'Ⅱ ПАУЗА',exact:true}).click();await shot('04-pause-640x360');await p.getByRole('button',{name:'ПРОДОЛЖИТЬ',exact:true}).click();
 // Input: actual touch outside HUD changes position, touch on HUD does not.
 await p.evaluate(()=>{scene21.__os.vx=0;scene21.__os.vy=0;});const x0=await p.evaluate(()=>scene21.__os.x);const cd=await c.newCDPSession(p);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:420,y:180}]});await p.waitForTimeout(450);await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(Math.abs(await p.evaluate(()=>scene21.__os.x)-x0)>1);r.checks.push('touch gameplay, journal and pause');
 await p.evaluate(()=>{const s=scene21.__os;Object.assign(s,{x:1800,y:900,vx:0,vy:0,inv:999});scene21.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);scene21.__osCam={x:s.x,y:s.y};});await p.keyboard.down('w');let smallest=Infinity;for(let i=0;i<35;i++){await p.waitForTimeout(80);const y=await p.evaluate(()=>{const m=scene21.__mobile21,s=scene21.__os,cam=scene21.__osCam;return m.height/2+(s.y-cam.y)*2*m.height/1080;});smallest=Math.min(smallest,y);}await p.keyboard.up('w');r.shipMinY=smallest;assert(smallest>=90);await shot('05-ship-safe-upward');
 for(const s of ['upgrades','sectorSelect','result','fail','resetConfirm','confirm17','settings17']){await state(s);await shot('06-'+s);const a=await audit();for(const b of a.card)assert(b.y>=-1&&b.bottom<=a.viewport.h+1,'modal clips '+s);r.checks.push(s+' bounds');}
 // Real native action bridge: purchase, persistence, reset cancellation.
 await p.evaluate(()=>{const v=scene21.getVariables();v.get('Credits').setNumber(500);v.get('TechParts').setNumber(2);});await state('upgrades');await p.locator('[data-native="UpgradeButtonBg"]').first().click();await p.waitForTimeout(350);r.purchase=await p.evaluate(()=>({credits:scene21.getVariables().get('Credits').getAsNumber(),save:localStorage.getItem('orbitalSalvageSave')}));assert(r.purchase.credits<500);assert(r.purchase.save);await p.locator('[data-native="ResetButtonBg"]').click();await p.waitForFunction(()=>__osQAState.state==='resetConfirm');await p.locator('[data-native="ResetConfirmCancelBg"]').click();await p.waitForFunction(()=>__osQAState.state==='upgrades');r.checks.push('native purchase/save and reset cancel');
 await state('menu');await p.getByRole('button',{name:'ОРБИТАЛЬНЫЙ ПАТРУЛЬ',exact:true}).click();await p.waitForTimeout(400);await shot('07-arcade');await p.getByRole('button',{name:'ВЫЙТИ ИЗ ПАТРУЛЯ',exact:true}).click();
 for(const[w,h]of[[844,390],[844,300],[640,280],[390,844],[412,915],[360,800]]){await p.setViewportSize({width:w,height:h});await p.waitForTimeout(300);await state(h>w?'rotate':'play');await shot('08-size-'+w+'x'+h);r.checks.push(w+'x'+h);}
 await p.setViewportSize({width:844,height:390});await state('play');await p.evaluate(()=>{const e=document.documentElement;e.style.setProperty('--safe-left','28px');e.style.setProperty('--safe-right','20px');e.style.setProperty('--safe-top','8px');e.style.setProperty('--safe-bottom','12px');scene21.__mobile21.refresh();});await p.waitForTimeout(200);await shot('09-safe-insets');r.safe=await audit();assert(r.safe.hud.x>=28);assert(r.safe.toolbar.right<=824);
 await p.reload();await p.waitForFunction(()=>__osQAState?.state==='menu');r.checks.push('reload existing save');await shot('10-reload');assert(!r.errors.length);r.pass=true;
}catch(e){r.failure=e.stack;console.error(e);}finally{await browser.close();fs.writeFileSync('docs/mobile21-qa.json',JSON.stringify(r,null,2));console.log(JSON.stringify({...r,purchase:r.purchase?{credits:r.purchase.credits,saved:true}:null},null,2));}
})();
