const {open,read,click,fs,path,root,assert}=require('./release15-qa-lib');
(async()=>{const report={mode:'responsive UI, isolated state fixtures and real mouse/touch input',views:[],ads:[]},dir=path.join(root,'_tmp-export/release15-responsive');fs.mkdirSync(dir,{recursive:true});
for(const [w,h,mobile]of[[1920,1080,false],[1600,900,false],[1366,768,false],[1280,720,false],[1280,720,true],[720,1280,true]]){const q=await open({width:w,height:h},mobile),p=q.p,item={w,h,mobile};try{await p.screenshot({path:path.join(dir,`${w}-${h}-${mobile}-menu.png`)});if(w<h){item.rotate=(await read(p)).state==='rotate';continue;}
await click(p,'ButtonBg');assert.equal((await read(p)).state,'play');await p.waitForTimeout(350);const before=await read(p);await p.mouse.move(w*.9,h*.6);await p.waitForTimeout(500);const after=await read(p);item.hoverDoesNotSteer=Math.hypot(after.shipX-before.shipX,after.shipY-before.shipY)<1;assert.ok(item.hoverDoesNotSteer);
if(mobile){await p.dispatchEvent('canvas','pointerdown',{pointerType:'touch',clientX:w*.8,clientY:h*.6,buttons:1});await p.waitForTimeout(650);await p.dispatchEvent('canvas','pointerup',{pointerType:'touch',clientX:w*.8,clientY:h*.6,buttons:0});const t=await read(p);item.touchMoves=Math.hypot(t.shipX-after.shipX,t.shipY-after.shipY)>20;assert.ok(item.touchMoves);}
await p.screenshot({path:path.join(dir,`${w}-${h}-${mobile}-play.png`)});
for(const st of ['result','upgrades','sectorSelect','resetConfirm','fail']){await p.evaluate(st=>scene15.getVariables().get('GameState').setString(st),st);await p.waitForTimeout(100);await p.screenshot({path:path.join(dir,`${w}-${h}-${mobile}-${st}.png`)});if(st==='fail'){item.deathButtons=await p.evaluate(()=>scene15.getObjects('ResultButtonBg').filter(o=>!o.isHidden()).length);assert.equal(item.deathButtons,1);}}
if(w===1920){await click(p,'RewardButtonBg');assert.equal((await read(p)).state,'play');report.ads.push('second chance');await p.evaluate(()=>{const v=scene15.getVariables();v.get('GameState').setString('result');v.get('DeliveredValue').setNumber(90);v.get('DoubleRewardUsed').setNumber(0);});await p.waitForTimeout(100);const c=(await read(p)).credits;await click(p,'RewardButtonBg');assert.equal((await read(p)).credits,c+90);report.ads.push('double');await click(p,'ResultButtonBg');const offers=(await read(p)).offers.join();await click(p,'SystemButtonBg');assert.notEqual((await read(p)).offers.join(),offers);report.ads.push('reroll');await p.evaluate(()=>{const v=scene15.getVariables();v.get('SectorUnlocked').setNumber(1);v.get('GameState').setString('sectorSelect');});await p.waitForTimeout(100);await click(p,'SectorSelectButtonBg',1);assert.equal((await read(p)).sector,2);assert.equal((await read(p)).state,'play');item.sector2Click=true;}
item.render=await p.evaluate(()=>{const c=document.querySelector('canvas');return{inner:[innerWidth,innerHeight],dpr:devicePixelRatio,css:[c.clientWidth,c.clientHeight],backing:[c.width,c.height]};});
}catch(e){item.failure=e.stack;console.error(w,h,e.message);}finally{item.errors=q.errors;report.views.push(item);await q.browser.close();}}
fs.writeFileSync(path.join(root,'docs/release15-ui.json'),JSON.stringify(report,null,2));})();
