const {open,click,read,fs,assert}=require('./release17-qa-lib');
(async()=>{const q=await open({width:1366,height:768}),p=q.p,out='screenshots/FinalPreRelease17',r={mode:'targeted UI/visual fixtures, not natural progression'};const shot=async n=>{await p.waitForTimeout(90);await p.evaluate(()=>scene15.__os.inv=0);await p.waitForTimeout(20);await p.screenshot({path:out+'/'+n+'.png'});};try{
await shot('01-main-menu');await click(p,'ButtonBg');await shot('02-sector1-start');await p.keyboard.press('Escape');await shot('13-pause-menu');await p.getByRole('button',{name:'ПРОДОЛЖИТЬ',exact:true}).click();
await p.getByRole('button',{name:'DEV',exact:true}).click();await p.getByRole('button',{name:'ПОКАЗАТЬ POI',exact:true}).click();await p.getByRole('button',{name:'ПОКАЗАТЬ ОПАСНОСТИ',exact:true}).click();await shot('30-dev-panel');r.debug=await p.evaluate(()=>({poi:scene15.__ui17.poi,hazards:scene15.__ui17.hazards}));assert.ok(r.debug.poi&&r.debug.hazards);
await p.getByRole('button',{name:'МЕТЕОРНЫЙ ПОТОК',exact:true}).click();await p.getByRole('button',{name:'DEV',exact:true}).click();await p.evaluate(()=>scene15.__os.onboarding=false);r.meteorDistance=await p.evaluate(()=>{const r=scene15.__g13.regions.find(r=>r.id==='meteor');return Math.hypot(scene15.__os.x-r.x,scene15.__os.y-r.y)});assert.ok(r.meteorDistance<450);await shot('10-meteor-warning');await p.waitForTimeout(1200);await shot('06-meteor-region');
await p.getByRole('button',{name:'DEV',exact:true}).click();await p.getByRole('button',{name:'ПОГОНЯ',exact:true}).click();await p.getByRole('button',{name:'DEV',exact:true}).click();await p.waitForTimeout(2900);r.chase=await p.evaluate(()=>({phase:scene15.__g13.chase16.phase,visible:scene15.getObjects('Chaser16').filter(o=>!o.isHidden()).length}));assert.equal(r.chase.phase,'chasing');assert.equal(r.chase.visible,2);await shot('11-meteor-chase');
await p.evaluate(()=>{const g=scene15.__g13,s=scene15.__os,v=scene15.getVariables();g.chase16.phase='idle';g.secret.stage=0;const t=g.loot.find(o=>o.kind==='energy');Object.assign(s,{x:t.x-75,y:t.y+45,vx:0,vy:0,inv:0,floatLife:0,toast:0});scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);scene15.__osCam={x:s.x,y:s.y};v.get('Hull').setNumber(3);scene15.__radio16.life=0;});await shot('09-loot-readability');
await p.evaluate(()=>{const v=scene15.getVariables(),g=scene15.__g13,s=scene15.__os;v.get('ContractsCompleted').setNumber(2);scene15.__osMission();v.get('ScrapCount').setNumber(3);g.chain17=null;const t=g.pois.find(p=>p.primary&&p.region===1);s.x=t.x-45;s.y=t.y+40;s.vx=s.vy=0;scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);scene15.__osCam={x:s.x,y:s.y};});await p.waitForTimeout(700);await shot('12-multistage-contract');
await p.evaluate(()=>{const v=scene15.getVariables();v.get('GameState').setString('result');v.get('DeliveredValue').setNumber(75);v.get('ContractRewardEarned').setNumber(130);v.get('CargoValue').setNumber(75);v.get('ScrapCount').setNumber(6);v.get('ContainerCount').setNumber(0);v.get('StreakBonus').setNumber(15);v.get('Credits').setNumber(205);});await shot('27-result');await click(p,'ResultButtonBg');await shot('28-upgrades');
await p.evaluate(()=>{scene15.getVariables().get('SectorUnlocked').setNumber(1);scene15.getVariables().get('GameState').setString('sectorSelect');});await shot('14-sector-select');await click(p,'SectorSelectButtonBg',1);assert.equal((await read(p)).sector,2);await shot('15-sector2-start');
// Explicitly select the beam cycle for screenshot labels (not traversal QA).
for(const[phase,name]of[[.15,'22-secret-laser-warning'],[1.2,'23-secret-laser-active']]){await p.evaluate(phase=>{const g=scene15.__g13,s=scene15.__os;g.secret.stage=4;g.secret.template=0;g.secret.progress=0;g.secret.map15=scene15.__secretModel15(0);const t=g.secret.map15.gates[0];s.x=t.x-65;s.y=t.y+65;s.vx=s.vy=0;s.phase=phase;s.inv=0;s.floatLife=0;s.toast=0;scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);scene15.__osCam={x:s.x,y:s.y};scene15.__radio16.life=0;},phase);await shot(name);}
await q.context.route('http://orbital-release.test/**',async route=>{const u=new URL(route.request().url());const response=await route.fetch({url:'http://127.0.0.1:4234'+u.pathname+u.search});await route.fulfill({response});});await p.goto('http://orbital-release.test/index.html');await p.waitForFunction(()=>window.__osQAState?.state==='menu');r.productionDevHidden=await p.getByRole('button',{name:'DEV',exact:true}).isHidden();assert.ok(r.productionDevHidden);
}catch(e){r.failure=e.stack;console.error(e);}finally{r.errors=q.errors;fs.writeFileSync('docs/release17-proof.json',JSON.stringify(r,null,2));await q.browser.close();}})();
