const {open,click,read,fs,path,root,assert}=require('./release16-qa-lib');
(async()=>{const q=await open({width:1366,height:768}),p=q.p,out=path.join(root,'screenshots/ReleaseProduction16'),r={mode:'targeted visual fixtures, not progression'};try{await click(p,'ButtonBg');const shot=async name=>{await p.waitForTimeout(70);await p.screenshot({path:path.join(out,name+'.png')});};
await p.evaluate(()=>{const v=scene15.getVariables(),s=scene15.__os;v.get('CurrentSector').setNumber(2);v.get('ContractsCompleted').setNumber(14);scene15.__osMission();scene15.__g13Generate(530051);const t=scene15.__g13.pois[1];s.x=t.x-120;s.y=t.y+80;s.vx=s.vy=0;s.inv=0;scene15.__osCam={x:s.x,y:s.y};scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);v.get('RunTime').setNumber(21);});await shot('mission-chain');
await p.evaluate(()=>{const v=scene15.getVariables();v.get('Cargo').setNumber(v.get('CargoMax').getAsNumber());v.get('CargoValue').setNumber(96);});await shot('cargo-full');
await p.evaluate(()=>{const s=scene15.__os;s.floatText='СЕРИЯ x3\nБОНУС +5';s.floatLife=1;});await shot('streak');
await p.evaluate(()=>{const s=scene15.__os,g=scene15.__g13,h=g.hazards[0];s.x=h.x;s.y=h.y;s.vx=s.vy=0;s.inv=0;scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);scene15.__osCam={x:s.x,y:s.y};scene15.getVariables().get('Hull').setNumber(3);});await shot('hit');r.collision=(await read(p)).hull<3;assert.ok(r.collision);
await p.evaluate(()=>{const v=scene15.getVariables();v.get('GameState').setString('upgrades');v.get('Credits').setNumber(700);['buffer','containment','salvage'].forEach((id,i)=>v.get('Offer'+(i+1)).setString(id));});await shot('new-modules');
await p.evaluate(()=>{scene15.getVariables().get('GameState').setString('play');const g=scene15.__g13,s=scene15.__os,r=g.regions.find(r=>r.index>2&&r.haz>=4);s.x=r.x;s.y=r.y;s.vx=s.vy=0;s.inv=0;scene15.getVariables().get('Hull').setNumber(3);g.chase16={phase:'idle',time:0,used:[],bodies:[]};scene15.getObjects('Ship')[0].setCenterPositionInScene(s.x,s.y);scene15.__osCam={x:s.x,y:s.y};});await shot('chase-warning');await p.waitForTimeout(2800);await shot('meteor-chase');r.chase=await p.evaluate(()=>scene15.__g13.chase16.phase);assert.equal(r.chase,'chasing');
}catch(e){r.failure=e.stack;console.error(e);}finally{r.errors=q.errors;fs.writeFileSync(path.join(root,'docs/release16-proof.json'),JSON.stringify(r,null,2));await q.browser.close();}})();
