const {launch,steer,state,sleep,fs,path,root,assert}=require('./smart08-play');
const url='http://127.0.0.1:4231/index.html',out=path.join(root,'screenshots/FullReleaseRebuild14');fs.mkdirSync(out,{recursive:true});
async function bind(p){await p.evaluate(()=>{const f=gdjs.RuntimeScene.prototype.renderAndStep;gdjs.RuntimeScene.prototype.renderAndStep=function(...a){window.qaScene=this;return f.apply(this,a);};});await p.waitForFunction(()=>window.qaScene);}
async function click(p,n,i=0){const r=await p.evaluate(([n,i])=>{const o=qaScene.getObjects(n)[i],c=document.querySelector('canvas').getBoundingClientRect();return [c.x+(o.getX()+o.getWidth()/2)*c.width/1920,c.y+(o.getY()+o.getHeight()/2)*c.height/1080];},[n,i]);await p.mouse.click(...r);await sleep(p,230);}
const read=p=>p.evaluate(()=>({g:qaScene.__g13,prices:qaScene.__osMap.prices,phase:qaScene.__os.phase,save:localStorage.getItem('orbitalSalvageSave')}));
async function natural(index){const b=await launch(url),p=b.p,t=Date.now(),events=[];await bind(p);const shot=async name=>Number(index)===2?null:p.screenshot({path:path.join(out,name+'.png')}),log=async name=>{const e={event:name,seconds:(Date.now()-t)/1000,state:await state(p)};events.push(e);console.log(JSON.stringify(e));};
 try{await shot('01-menu');await click(p,'ButtonBg');await log('fresh-start');await shot('02-sector1-start');
 for(let run=0;run<12;run++){
 let st=await state(p);if(st.state!=='play')throw Error('Natural route stopped: '+st.state);
 const type=st.missionType;
 for(let i=0;i<12;i++){st=await state(p);if(st.state!=='play')throw Error('Natural death');if(st.cargo>=st.cargoMax||st.missionProgress>=st.missionTarget||type==='nodamage'&&st.cargo>=4)break;
 const {g}=await read(p),kind=type==='container'?'heavy':type==='valuable'?'energy':'scrap',targets=g.loot.filter(l=>!l.taken&&l.kind===kind).sort((a,b)=>Math.hypot(a.x-st.shipX,a.y-st.shipY)-Math.hypot(b.x-st.shipX,b.y-st.shipY));if(!targets.length)break;await steer(p,targets[0].x,targets[0].y,27);await log('loot');}
 await shot('03-working-orbit');await steer(p,260,700,100);await log('return');assert.equal((await state(p)).state,'result');await shot('09-result');await click(p,'ResultButtonBg');st=await state(p);const {prices}=await read(p),id=st.offers.findIndex(id=>prices[id]<=st.credits);if(id>=0){const before=st.credits,cost=prices[st.offers[id]];await click(p,'UpgradeButtonBg',id);assert.equal((await state(p)).credits,before-cost,'one click must buy exactly one offer');await log('upgrade');}await shot('11-upgrades');await click(p,'UpgradeBackButtonBg');st=await state(p);if(st.state==='sectorSelect'){await shot('12-sector-select');await click(p,'SectorSelectButtonBg',1);await log('sector2');break;}}
 assert.equal((await state(p)).sector,2);await shot('13-sector2-start');let {g}=await read(p);
 for(const [name,target] of [['signal',g.signal],['key',g.key],['gate',g.gate]]){await steer(p,target.x,target.y,30);await log(name);await shot(name==='signal'?'15-signal-locked':name==='key'?'16-access-key':'17-gate-active');assert.equal((await state(p)).state,'play');}
 await p.waitForFunction(()=>qaScene.__g13.secret.stage===4,{},{timeout:5000});await shot('18-secret-entry');
 for(let i=0;i<6;i++){g=(await read(p)).g;const target=g.secret.route[i],x=5070+i*175;await steer(p,x-85,target[1],27);await sleep(p,450);
 await p.waitForFunction(i=>{const phase=(qaScene.__os.phase+i*.47+(qaScene.__g13.secret.template%4)*.31)%4;return phase>2.15&&phase<2.4;},i,{timeout:6000});await steer(p,target[0],target[1],27);await log('safe-pocket-'+(i+1));await shot(i<3?'19-laser-room-1':'20-laser-room-2');assert.equal((await state(p)).state,'play');}
 g=(await read(p)).g;await shot('21-secret-cache');await steer(p,6090,g.secret.route[5][1],27);await log('cache');await shot('22-secret-reward');await sleep(p,2300);assert.equal((await read(p)).g.secret.cache,true);await steer(p,260,700,100);await log('secret-return');assert.equal((await state(p)).state,'result');const saved=(await read(p)).save;await p.reload();await p.waitForFunction(()=>window.__osQAState?.state==='menu');assert.equal(await p.evaluate(()=>localStorage.getItem('orbitalSalvageSave')),saved);await log('reload');
 }catch(e){events.push({failure:e.message});console.error(e);}finally{fs.writeFileSync(path.join(root,'docs',`release14-natural-${index}.json`),JSON.stringify({events,errors:b.errors},null,2));await b.browser.close();}}
async function responsive(){const report=[];for(const [width,height,mobile] of [[1920,1080,false],[1600,900,false],[1366,768,false],[1280,720,false],[1280,720,true],[720,1280,true]]){const b=await launch(url,{width,height},mobile);await bind(b.p);const filename=mobile?(height>width?'24-mobile-portrait':'23-mobile-landscape'):`responsive-${width}`;await b.p.screenshot({path:path.join(out,filename+'.png')});if(height<width){await click(b.p,'ButtonBg');const before=await state(b.p);await b.p.mouse.move(1100,650);await sleep(b.p,500);const after=await state(b.p);assert.equal(after.shipX,before.shipX);await b.p.keyboard.down('d');await sleep(b.p,500);await b.p.keyboard.up('d');assert.ok((await state(b.p)).shipX>after.shipX);if(mobile){await b.p.touchscreen.tap(1000,400);await sleep(b.p,500);}await b.p.screenshot({path:path.join(out,filename+'.png')});}report.push({width,height,mobile,errors:b.errors});await b.browser.close();}fs.writeFileSync(path.join(root,'docs/release14-responsive.json'),JSON.stringify(report,null,2));}
async function seeds(){const b=await launch(url),p=b.p;await bind(p);await click(p,'ButtonBg');const rows=[];for(const seed of [130013,230027,330037,430049,530051,630061,730069,830077,930079,1030087]){const row=await p.evaluate(seed=>{qaScene.__g13Generate(seed);return qaScene.__g13.validation;},seed);assert.equal(row.seed,seed);assert.ok(row.stationSafe);rows.push(row);}fs.writeFileSync(path.join(root,'docs/release14-seeds.json'),JSON.stringify({mode:'explicit generation fixture, not natural gameplay',seeds:rows,errors:b.errors},null,2));await b.browser.close();}
(async()=>{if(process.argv[2]==='responsive')await responsive();else if(process.argv[2]==='seeds')await seeds();else await natural(process.argv[2]||1);})().catch(e=>{console.error(e);process.exitCode=1});
