module.exports=function setup16(scene){
 if(scene.__release16)return;scene.__release16=true;
 const v=scene.getVariables(),num=k=>v.get(k).getAsNumber(),str=k=>v.get(k).getAsString();
 const mods={buffer:['BufferLevel',240,'ДЕМПФЕР','После удара: 1,1 с защиты'],containment:['ContainmentLevel',260,'ИЗОЛЯЦИЯ','Первый удар радиации поглощён'],salvage:['SalvageLevel',280,'СОРТИРОВЩИК','+20% стоимости энергоячеек'],decoder:['DecoderLevel',300,'ДЕШИФРАТОР','+60 за секретный тех-кэш']};scene.__modules16=mods;
 let saved={};try{saved=JSON.parse(localStorage.getItem('orbitalSalvageSave')||'{}')}catch{}
 for(const [id,[key,cost]]of Object.entries(mods)){v.get(key).setNumber(Number(saved[key])||0);scene.__osMap.prices[id]=cost;}
 const save=scene.__osSave,done=scene.__osModuleDone,installed=scene.__osInstalledCount;
 scene.__osSave=()=>{save();try{const data=JSON.parse(localStorage.getItem('orbitalSalvageSave')||'{}');for(const [, [key]]of Object.entries(mods))data[key]=num(key);data.AudioEnabled16=scene.__audio16?.enabled??true;localStorage.setItem('orbitalSalvageSave',JSON.stringify(data));}catch(e){console.warn('Сохранение модулей',e)}};
 scene.__osModuleDone=id=>mods[id]?num(mods[id][0])>0:done(id);
 const ids=['cargo','engine','hull','magnet','radar','insurance','shield','assist','contract','repair','scanner',...Object.keys(mods)];
 scene.__osInstalledCount=()=>ids.filter(scene.__osModuleDone).length;
 scene.__osAvailable=()=>ids.filter(id=>!scene.__osModuleDone(id)).length;
 scene.__osOffers=()=>{const pool=ids.filter(id=>!scene.__osModuleDone(id));for(let i=0;i<3;i++)v.get('Offer'+(i+1)).setString(i<pool.length?pool[(num('OfferSeed')+i)%pool.length]:'done');v.get('OffersReady').setNumber(1)};
 const gen=scene.__g13Generate;scene.__g13Generate=seed=>{gen(seed);scene.__world16(scene.__g13,num('CurrentSector'),{scrap:scene.getObjects('ProcScrap').length,energy:scene.getObjects('ProcEnergy').length,data:scene.getObjects('ProcData').length,heavy:scene.getObjects('ProcHeavy').length,decor:scene.getObjects('ProcDecor').length,pois:scene.getObjects('ProcPOI').length,hazards:scene.getObjects('ProcHazard').length});scene.__g13.secret.template=scene.__g13.seed%8;};
 const mission=scene.__osMission;
 const extra=[['rescue','ЭХО КАРАВАНА',3,145,1,0],['calibrate','ЦЕПЬ РЕТРАНСЛЯТОРОВ',3,130,1,0],['expedition','ЗА ГРАНИЦЕЙ КАРТ',3,150,1,0],['streak','ЧИСТАЯ РАБОТА',5,105,0,0],['pursuit','ОТОРВАТЬСЯ ОТ ПРЕСЛЕДОВАНИЯ',1,140,1,0],['anomaly','АРХИВ АНОМАЛИИ',3,165,1,130]];
 scene.__missions16=extra;
 scene.__osMission=()=>{mission();const n=num('ContractsCompleted')%20;if(n>=14){const m=extra[n-14];for(const[k,i]of[['MissionType',0],['Mission',1]])v.get(k).setString(m[i]);for(const[k,i]of[['MissionTarget',2],['MissionReward',3],['MissionTechReward',4],['MissionTimeLimit',5]])v.get(k).setNumber(m[i]);}scene.__radio16={text:'ДИСПЕТЧЕР / '+str('Mission')+'. Возвращайтесь с грузом — станция ждёт.',life:6};};
 // Audio is gesture-unlocked, bounded, and silenced on background/ad pause.
 const audio={ctx:null,enabled:saved.AudioEnabled16!==false,music:false,voices:0,events:[],last:{},nextAmbient:0};scene.__audio16=audio;
 audio.unlock=()=>{if(!audio.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio.ctx=new AC();audio.master=audio.ctx.createGain();audio.master.gain.value=.18;audio.master.connect(audio.ctx.destination);}audio.ctx.resume().catch(()=>{});};
 audio.tone=(kind)=>{if(!audio.ctx||!audio.enabled||audio.ctx.state!=='running'||audio.voices>12||document.hidden)return;const now=audio.ctx.currentTime;if(now-(audio.last[kind]||-10)<.09)return;audio.last[kind]=now;const notes={click:[440,660],hover:[300],pickup:[660,990],hit:[110,65],contract:[440,554,660,880],gate:[180,360,720],warning:[240,180],fail:[220,165,110],start:[330,440,660],ambient:[110,165,220]}[kind]||[440];audio.events.push({kind,time:now});if(audio.events.length>100)audio.events.shift();notes.forEach((f,i)=>{const o=audio.ctx.createOscillator(),a=audio.ctx.createGain(),t=now+i*.065,d=kind==='ambient'?2.5:.16;o.type=kind==='hit'?'triangle':'sine';o.frequency.setValueAtTime(f,t);a.gain.setValueAtTime(0,t);a.gain.linearRampToValueAtTime(kind==='ambient'?.045:.3,t+.018);a.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(a);a.connect(audio.master);o.start(t);o.stop(t+d+.02);audio.voices++;o.onended=()=>{o.disconnect();a.disconnect();audio.voices--;};});};
 document.addEventListener('pointerdown',audio.unlock,{passive:true});document.addEventListener('keydown',audio.unlock,{passive:true});
 document.addEventListener('visibilitychange',()=>{if(audio.ctx)audio.master.gain.setTargetAtTime(document.hidden?0:audio.enabled?.18:0,audio.ctx.currentTime,.04);});
 const root=document.createElement('div');root.id='orbital-tools16';root.style.cssText='position:fixed;bottom:18px;right:22px;z-index:9000;display:flex;gap:10px;font:16px Arial';document.body.appendChild(root);
 const btn=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.style.cssText='border:1px solid #57aac0;border-radius:8px;background:#102b40;color:#dceef1;padding:12px 18px;cursor:pointer;font:600 15px Arial;';b.addEventListener('pointerenter',()=>{b.style.background='#23536a';audio.tone('hover');});b.addEventListener('pointerleave',()=>b.style.background='#102b40');b.addEventListener('pointerdown',e=>{e.stopPropagation();b.style.transform='translateY(2px)';});b.addEventListener('pointerup',e=>{e.stopPropagation();b.style.transform='';});b.onclick=e=>{e.stopPropagation();audio.unlock();audio.tone('click');fn();};root.appendChild(b);return b;};
 const sound=btn('ЗВУК: ВКЛ',()=>{audio.enabled=!audio.enabled;sound.textContent=audio.enabled?'ЗВУК: ВКЛ':'ЗВУК: ВЫКЛ';try{const data=JSON.parse(localStorage.getItem('orbitalSalvageSave')||'{}');data.AudioEnabled16=audio.enabled;localStorage.setItem('orbitalSalvageSave',JSON.stringify(data));}catch{}});sound.textContent=audio.enabled?'ЗВУК: ВКЛ':'ЗВУК: ВЫКЛ';
 const music=btn('АМБИЕНТ: ВЫКЛ',()=>{audio.music=!audio.music;music.textContent=audio.music?'АМБИЕНТ: ВКЛ':'АМБИЕНТ: ВЫКЛ';});
 const arcade=btn('АРКАДА',()=>{v.get('GameState').setString('arcade');arc.start();});
 const panel=document.createElement('div');panel.style.cssText='display:none;position:fixed;inset:0;background:radial-gradient(ellipse at top,#17344c,#071320);z-index:8000;align-items:center;justify-content:center';document.body.appendChild(panel);
 const cv=document.createElement('canvas');cv.width=960;cv.height=600;cv.style.cssText='position:relative;width:min(92vw,1120px);height:auto;max-height:85vh;border:1px solid #42778f;border-radius:14px;touch-action:none';panel.appendChild(cv);const ctx=cv.getContext('2d');const art={};for(const[k,src]of Object.entries(scene.__arcadeArt16)){art[k]=new Image();art[k].src=src;}
 const arc={active:false,score:0,lives:3,x:480,clock:0,spawn:0,shot:0,keys:{},rocks:Array.from({length:18},()=>({active:false})),shots:Array.from({length:24},()=>({active:false})),start(){this.active=true;this.score=0;this.lives=3;this.clock=0;this.spawn=0;this.rocks.forEach(o=>o.active=false);this.shots.forEach(o=>o.active=false);}};scene.__arcade16=arc;
 window.addEventListener('keydown',e=>{arc.keys[e.code]=true;if(str('GameState')==='arcade'&&e.code==='Escape'){v.get('GameState').setString('menu');arc.active=false;}});window.addEventListener('keyup',e=>arc.keys[e.code]=false);
 cv.addEventListener('pointermove',e=>{const r=cv.getBoundingClientRect();arc.x=Math.max(25,Math.min(935,(e.clientX-r.left)*960/r.width));});cv.addEventListener('pointerdown',e=>{e.stopPropagation();if(!arc.active)arc.start();});cv.addEventListener('pointerup',e=>e.stopPropagation());
 const back=btn('НАЗАД',()=>{v.get('GameState').setString('menu');arc.active=false;});
 scene.__shell16=dt=>{const st=str('GameState'),isArc=st==='arcade';panel.style.display=isArc?'flex':'none';root.style.display=['menu','arcade'].includes(st)?'flex':'none';arcade.style.display=st==='menu'?'':'none';back.style.display=isArc?'':'none';
 if(audio.ctx){audio.master.gain.setTargetAtTime(audio.enabled&&!document.hidden&&!scene.__os.rewardBusy?.18:0,audio.ctx.currentTime,.08);if(audio.music&&performance.now()>audio.nextAmbient&&!document.hidden&&!scene.__os.rewardBusy){audio.tone('ambient');audio.nextAmbient=performance.now()+4200;}}
 if(!isArc)return;ctx.fillStyle='#081b2c';ctx.fillRect(0,0,960,600);for(let i=0;i<70;i++){ctx.fillStyle=i%3?'#24465b':'#53869b';ctx.fillRect((i*167)%960,(i*113+arc.clock*18)%600,2,2);}ctx.font='600 20px Arial';ctx.fillStyle='#d5edf0';ctx.fillText('ОРБИТАЛЬНЫЙ ПАТРУЛЬ',32,36);ctx.fillText('ОЧКИ '+arc.score+'   КОРПУС '+arc.lives,610,36);ctx.font='16px Arial';ctx.fillText('← → / мышь / палец — движение • огонь автоматический • ESC — назад',32,578);
 if(arc.active){arc.clock+=dt;arc.spawn-=dt;arc.shot-=dt;if(arc.keys.ArrowLeft||arc.keys.KeyA)arc.x-=dt*400;if(arc.keys.ArrowRight||arc.keys.KeyD)arc.x+=dt*400;arc.x=Math.max(25,Math.min(935,arc.x));if(arc.spawn<=0){const o=arc.rocks.find(o=>!o.active);if(o)Object.assign(o,{active:true,x:40+Math.random()*880,y:-30,r:18+Math.random()*12,speed:65+Math.min(100,arc.clock*1.8)});arc.spawn=Math.max(.4,1.15-arc.clock*.007);}if(arc.shot<=0){const o=arc.shots.find(o=>!o.active);if(o)Object.assign(o,{active:true,x:arc.x,y:510});arc.shot=.19;}}
 for(const o of arc.shots)if(o.active){o.y-=dt*480;ctx.fillStyle='#92eff4';ctx.fillRect(o.x-2,o.y,4,15);if(o.y<0)o.active=false;}
 for(const o of arc.rocks)if(o.active){if(arc.active)o.y+=o.speed*dt;if(art.rock.complete)ctx.drawImage(art.rock,o.x-o.r,o.y-o.r,o.r*2,o.r*2);for(const b of arc.shots)if(b.active&&Math.hypot(b.x-o.x,b.y-o.y)<o.r+4){b.active=false;o.active=false;arc.score+=10;audio.tone('pickup');break;}if(o.y>545){o.active=false;arc.lives--;audio.tone('hit');if(arc.lives<=0)arc.active=false;}}
 if(art.ship.complete)ctx.drawImage(art.ship,arc.x-25,493,50,50);
 ctx.fillStyle='#0a2035';ctx.fillRect(0,0,960,55);ctx.font='600 20px Arial';ctx.fillStyle='#d5edf0';ctx.fillText('ОРБИТАЛЬНЫЙ ПАТРУЛЬ',32,36);ctx.fillText('ОЧКИ '+arc.score+'   КОРПУС '+arc.lives,610,36);
 if(!arc.active){ctx.fillStyle='#071321df';ctx.fillRect(190,200,580,170);ctx.fillStyle='#e7ece2';ctx.font='bold 32px Arial';ctx.fillText('ПАТРУЛЬ ЗАВЕРШЁН',280,257);ctx.font='21px Arial';ctx.fillText('Очки: '+arc.score+' • нажмите для повтора',270,312);}
 };
};
