const {open,read,click,go,steer,fs,path,root}=require('./release16-qa-lib');
(async()=>{const q=await open(),p=q.p,start=Date.now(),events=[],id=process.argv[2]||'1',out=path.join(root,'_tmp-export','release16-natural-'+id);fs.mkdirSync(out,{recursive:true});
const log=async name=>{const s=await read(p);events.push({name,seconds:(Date.now()-start)/1000,state:s});console.log(name,((Date.now()-start)/1000).toFixed(1),s.state,s.cargo,s.hull,s.contractsCompleted,s.credits);};
try{await click(p,'ButtonBg');await log('start');
for(let run=0;run<24;run++){let s=await read(p);if(s.state==='fail'){await click(p,'ResultButtonBg');continue;}if(s.state!=='play')break;
 if(['relay','signal','survey','rescue','calibrate','expedition','anomaly'].includes(s.missionType)){for(let j=0;j<4;j++){s=await read(p);if(s.state!=='play'||s.missionProgress>=s.missionTarget)break;const t=await p.evaluate(()=>scene15.__g13.mission16?.target);const target=t||s.pois[j]||s.regions[j];await go(p,target.x,target.y);await p.waitForTimeout(1700);await log('mission-step');}}
for(let n=0;n<15;n++){s=await read(p);if(s.state!=='play'||s.cargo>=s.cargoMax||s.missionProgress>=s.missionTarget||s.missionType==='nodamage'&&s.cargo>=6||s.missionType==='speed'&&s.cargo>=4)break;
let list=s.loot.filter(o=>!o.taken&&(s.missionType==='container'||s.missionType==='courier'||s.missionType==='speed'&&s.cargo===0?o.kind==='heavy':s.missionType==='valuable'?o.kind!=='scrap':s.missionType==='danger'?s.regions[o.region]?.haz>1:s.missionType==='blackbox'||s.missionType==='fragile'?o.kind==='data':s.missionType==='tech'?o.kind==='energy':s.missionType==='highrisk'?o.kind!=='scrap'&&s.regions[o.region]?.haz>=3:o.kind==='scrap'));list.sort((a,b)=>Math.hypot(a.x-s.shipX,a.y-s.shipY)-Math.hypot(b.x-s.shipX,b.y-s.shipY));if(!list.length)break;await go(p,list[0].x,list[0].y);await log('loot');}
if((await read(p)).state!=='play')continue;await go(p,260,700,80);await log('return');await p.screenshot({path:path.join(out,'result-'+run+'.png')});if((await read(p)).state!=='result')continue;
await click(p,'ResultButtonBg');s=await read(p);const ix=s.offers.findIndex(id=>s.prices[id]<=s.credits);if(ix>=0){await click(p,'UpgradeButtonBg',ix);await log('purchase');}await click(p,'UpgradeBackButtonBg');s=await read(p);
if(s.state==='sectorSelect'){await log('unlock');await click(p,'SectorSelectButtonBg',1);await log('sector2');s=await read(p);for(const[name,t]of[['signal',s.signal],['key',s.key],['gate',s.gate]]){await go(p,t.x,t.y,45);await log(name);if((await read(p)).state!=='play')break;}await p.waitForTimeout(1800);s=await read(p);if(s.secret.stage===4){const model=s.secret.map15;for(let i=0;i<model.points.length;i++){const pt=model.points[i],gate=model.gates.find(g=>g.idx===i);if(gate){for(let j=0;j<80;j++){s=await read(p);const c=(s.phase+gate.pattern*.38)%4.8;if(c>3.45&&c<3.7)break;await p.waitForTimeout(45);}}await steer(p,...pt,16);if(model.route.some(r=>r[0]===pt[0]&&r[1]===pt[1]))await p.waitForTimeout(1500);if((await read(p)).state!=='play')break;}await p.waitForTimeout(2600);await log('secret-end');s=await read(p);if(s.state==='play'){await go(p,260,700,80);await log('sector2-return');}}break;}
}
}catch(e){events.push({failure:e.stack});console.error(e);}finally{fs.writeFileSync(path.join(root,'docs','release16-natural-'+id+'.json'),JSON.stringify({mode:'fresh storage; keyboard and real clicks; coordinate-aware navigation; no game state writes',seconds:(Date.now()-start)/1000,events,errors:q.errors},null,2));await q.browser.close();}})();
