const base=require('./smart08-play');
async function open(viewport={width:1920,height:1080},mobile=false){const q=await base.launch('http://127.0.0.1:4232/index.html',viewport,mobile);await q.p.evaluate(()=>{const f=gdjs.RuntimeScene.prototype.renderAndStep;gdjs.RuntimeScene.prototype.renderAndStep=function(...a){window.scene15=this;return f.apply(this,a);};});await q.p.waitForFunction(()=>window.scene15);return q;}
const read=p=>p.evaluate(()=>{const s=scene15,g=s.__g13,v=s.getVariables();return{...window.__osQAState,loot:g.loot,hazards:g.hazards,regions:g.regions,structures:g.structures||[],secret:g.secret,signal:g.signal,key:g.key,gate:g.gate,pois:g.pois,prices:s.__osMap.prices,phase:s.__os.phase,vars:Object.fromEntries(['MissionReward','MissionTechReward','ContractRewardEarned','DeliveredValue','SpentCredits','MissionTimeLimit','ShieldLevel','RepairLevel'].map(k=>[k,v.get(k).getAsNumber()]))};});
async function click(p,name,i=0){const q=await p.evaluate(([n,i])=>{const o=scene15.getObjects(n)[i],c=document.querySelector('canvas').getBoundingClientRect();return{x:c.x+(o.getX()+o.getWidth()/2)*c.width/1920,y:c.y+(o.getY()+o.getHeight()/2)*c.height/1080};},[name,i]);await p.mouse.click(q.x,q.y);await p.waitForTimeout(220);}
// Read-only map navigation. Explicitly coordinate-aware; never called a human timing test.
function route(s,tx,ty){const step=35,W=179,H=87,key=(x,y)=>y*W+x,xy=k=>[k%W,Math.floor(k/W)];const blocked=(x,y)=>{const px=x*step,py=y*step;if(x<1||y<3||x>=W-1||y>=H-1)return true;return s.structures.some(w=>Math.abs(px-w.x)<w.w/2+55&&Math.abs(py-w.y)<w.h/2+55)||s.hazards.some(h=>Math.hypot(px-h.x,py-h.y)<65);};
const start=key(Math.round(s.shipX/step),Math.round(s.shipY/step)),gx=Math.round(tx/step),gy=Math.round(ty/step),goal=key(gx,gy),open=[start],cost=new Map([[start,0]]),parent=new Map(),closed=new Set();
let found=start;while(open.length&&closed.size<16000){let ix=0,best=Infinity;for(let i=0;i<open.length;i++){const [x,y]=xy(open[i]),v=cost.get(open[i])+Math.hypot(gx-x,gy-y);if(v<best){best=v;ix=i;}}const k=open.splice(ix,1)[0];if(k===goal){found=k;break;}if(closed.has(k))continue;closed.add(k);const [x,y]=xy(k);for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const nx=x+dx,ny=y+dy,n=key(nx,ny);if(closed.has(n)||n!==goal&&blocked(nx,ny)||dx&&dy&&(blocked(x+dx,y)||blocked(x,y+dy)))continue;const c=cost.get(k)+Math.hypot(dx,dy);if(c<(cost.get(n)??Infinity)){cost.set(n,c);parent.set(n,k);open.push(n);}}}
if(found!==goal)throw Error('No safe route to '+tx+','+ty);const points=[];for(let k=goal;k!==start;k=parent.get(k)){if(k===undefined)throw Error('route chain');points.push(xy(k).map(v=>v*step));}points.reverse();const simple=[];let prev=[s.shipX,s.shipY],direction='';for(let i=0;i<points.length;i++){const a=points[i],d=[Math.sign(a[0]-prev[0]),Math.sign(a[1]-prev[1])].join(',');if(direction&&d!==direction)simple.push(points[i-1]);direction=d;prev=a;}simple.push([tx,ty]);return simple;}
async function move(p,x,y,tolerance=25){const initial=await base.state(p),held=new Set(),start=Date.now(),budget=Math.max(14000,Math.hypot(x-initial.shipX,y-initial.shipY)/130*1000+5000);try{while(Date.now()-start<budget){const s=await base.state(p);if(s.state!=='play'||initial.secretStage<4&&s.secretStage>=4)return;const dx=x-s.shipX,dy=y-s.shipY;if(Math.hypot(dx,dy)<tolerance)return;const want=new Set();if(Math.abs(dx)>12)want.add(dx>0?'d':'a');if(Math.abs(dy)>12)want.add(dy>0?'s':'w');for(const k of held)if(!want.has(k)){await p.keyboard.up(k);held.delete(k);}for(const k of want)if(!held.has(k)){await p.keyboard.down(k);held.add(k);}await p.waitForTimeout(70);}throw Error('Navigation stalled at '+x+','+y+' actual '+JSON.stringify(await base.state(p)));}finally{for(const k of held)await p.keyboard.up(k);await p.waitForTimeout(120);}}
async function go(p,x,y,tolerance=25){const s=await read(p),points=route(s,x,y);for(let i=0;i<points.length;i++){const [a,b]=points[i];await move(p,a,b,i===points.length-1?tolerance:20);const now=await base.state(p);if(now.state!=='play'||s.secretStage<4&&now.secretStage>=4)break;}}
module.exports={...base,open,read,click,go,route};
