// Assemble evidence from completed tests; never substitutes current runtime seed.
const fs=require('fs'),cp=require('child_process'),path=require('path');
const load=n=>JSON.parse(fs.readFileSync(n,'utf8')),save=(n,v)=>fs.writeFileSync(n,JSON.stringify(v,null,2)+'\n');
const runs=['complete-2','complete-3'].map((id,i)=>{const r=load('_tmp-export/release15-natural-'+id+'/report.json');const events=r.events.map(e=>({name:e.name,seconds:e.seconds,failure:e.failure,state:e.state&&Object.fromEntries(['state','seed','cargo','cargoMax','hull','hullMax','credits','techParts','contractsCompleted','missionType','missionProgress','missionTarget','sector','runTime','cargoValue','offers','vars','shipX','shipY'].map(k=>[k,e.state[k]])),secret:e.state&&{stage:e.state.secret.stage,cache:e.state.secret.cache,progress:e.state.secret.progress,template:e.state.secret.template}}));
const first=n=>events.find(e=>e.name===n),last=events.at(-1);const result={mode:r.mode,seconds:r.seconds,firstSeed:first('start').state.seed,firstLoot:first('loot').seconds,firstReturn:first('return').seconds,firstUpgrade:first('purchase').seconds,sector2Unlock:first('unlock').seconds,sector2Enter:first('sector2').seconds,secretSeconds:first('secret-end').seconds-first('gate').seconds,complete:last.name==='sector2-return'&&last.secret.cache&&last.state.state==='result',events,errors:r.errors};if(!result.complete)throw Error('Incomplete natural run '+id);save('docs/release15-natural-'+(i+1)+'.json',result);return result;});
const contracts=load('docs/release15-contracts.json'),seeds=load('docs/release15-seeds.json'),perf=load('docs/release15-performance.json'),screens=load('docs/release15-screens.json');
const staticAudit=JSON.parse(cp.execFileSync(process.execPath,['scripts/audit-project.js'],{encoding:'utf8'}));
const dimensions=screens.screens.map(s=>{const p=path.join('screenshots/ReleaseCandidatePolish15',s.file),b=fs.readFileSync(p);return{file:s.file,width:b.readUInt32BE(16),height:b.readUInt32BE(20)};});
save('docs/release15-summary.json',{baseCommit:'cf05c785f88a900fb221f9fe5c0149e266356919',staticAudit,natural:runs.map(({events,...r})=>r),hudNavigation:load('docs/release15-hud-navigation.json'),testedSeeds:seeds.seeds.map(s=>s.seed),traversal:load('docs/release15-traversal.json'),contracts:contracts.contracts.map(c=>({type:c.type,pass:c.pass})),performance:{seconds:perf.seconds,frames:perf.frames,heapStart:perf.samples[0].heap,heapEnd:perf.samples.at(-1).heap,minInstances:Math.min(...perf.samples.map(s=>s.instances)),maxInstances:Math.max(...perf.samples.map(s=>s.instances)),errors:perf.errors},screenshots:dimensions,visualReview:{openedAtOriginalSize:35,extraSeedViews:7,secondReview:true,notes:['Readable loot versus subdued decoration','No empty death action or clipped modal text in inspected views','Key remains an enlarged icon: art acceptance partial','Generic structural hardware repeats between region categories']},remaining:['First purchase varies by seed: optimal route can buy at 25.5 seconds; normal-player full progression timing not established','No new multi-stage mission chains; existing relay/survey/secret steps retained','Four shared structural layouts, not bespoke 3–5 layouts per region category; mirror not extended to new walls','Key art still icon-like; strong store-page artistic acceptance not claimed','Physical Android and production Yandex ads not tested'],verdict:'NOT READY'});
console.log('Evidence assembled: two complete fresh-save runs, twenty unique seeds, thirty-five PNGs.');
