const {open,read,click,fs,path,root,assert}=require('./release16-qa-lib');
(async()=>{const report={views:[],errors:[]},out=path.join(root,'screenshots/ReleaseProduction16');fs.mkdirSync(out,{recursive:true});
for(const[w,h,mobile]of[[1920,1080,false],[1600,900,false],[1366,768,false],[1280,720,false],[1536,864,false],[1917,920,false],[1280,720,true],[720,1280,true]]){
 const q=await open({width:w,height:h},mobile),p=q.p,r={w,h,mobile};try{
 const tag=w+'x'+h+(mobile?'-touch':'');await p.screenshot({path:path.join(out,tag+'-menu.png')});
 r.render=await p.evaluate(()=>{const c=document.querySelector('canvas'),b=c.getBoundingClientRect();return{inner:[innerWidth,innerHeight],canvas:[b.x,b.y,b.width,b.height],backing:[c.width,c.height]};});assert.ok(Math.abs(r.render.canvas[2]-w)<2&&Math.abs(r.render.canvas[3]-h)<2);
 if(w<h){r.rotate=(await read(p)).state==='rotate';assert.ok(r.rotate);continue;}
 await click(p,'ButtonBg');assert.equal((await read(p)).state,'play');const before=await read(p);await p.mouse.move(w*.9,h*.6);await p.waitForTimeout(300);const after=await read(p);r.mouseDoesNotSteer=Math.hypot(after.shipX-before.shipX,after.shipY-before.shipY)<1;assert.ok(r.mouseDoesNotSteer);
 if(mobile){await p.dispatchEvent('canvas','pointerdown',{pointerType:'touch',clientX:w*.75,clientY:h*.6,buttons:1});await p.waitForTimeout(500);await p.dispatchEvent('canvas','pointerup',{pointerType:'touch',clientX:w*.75,clientY:h*.6,buttons:0});r.touchDistance=Math.hypot((await read(p)).shipX-after.shipX,(await read(p)).shipY-after.shipY);assert.ok(r.touchDistance>25);}
 await p.screenshot({path:path.join(out,tag+'-hud.png')});
 r.panels=await p.evaluate(()=>{const s=scene15,g=s.getGame(),W=g.getGameResolutionWidth();return ['HudPanel','MissionPanel'].flatMap(n=>s.getObjects(n).map(o=>({n,x:o.getX(),y:o.getY(),w:o.getWidth(),h:o.getHeight(),left:o.getX()-960+W/2})));});
 for(const st of ['result','fail','upgrades','resetConfirm','sectorSelect']){await p.evaluate(st=>scene15.getVariables().get('GameState').setString(st),st);await p.waitForTimeout(100);await p.screenshot({path:path.join(out,tag+'-'+st+'.png')});}
 if(w===1920){await p.evaluate(()=>scene15.getVariables().get('GameState').setString('menu'));await p.waitForTimeout(100);await p.getByRole('button',{name:'АРКАДА',exact:true}).click();await p.waitForTimeout(1200);await p.mouse.move(930,700);await p.waitForTimeout(1200);await p.getByRole('button',{name:'АМБИЕНТ: ВЫКЛ'}).click();await p.waitForTimeout(500);r.arcade=await p.evaluate(()=>({score:scene15.__arcade16.score,lives:scene15.__arcade16.lives,pool:scene15.__arcade16.rocks.length+scene15.__arcade16.shots.length,audio:scene15.__audio16.ctx?.state,voices:scene15.__audio16.voices,events:scene15.__audio16.events}));await p.screenshot({path:path.join(out,'arcade.png')});assert.equal(r.arcade.audio,'running');assert.equal(r.arcade.pool,42);await p.getByRole('button',{name:'НАЗАД',exact:true}).click();await p.waitForTimeout(150);assert.equal((await read(p)).state,'menu');}
 }catch(e){r.failure=e.stack;console.error(e);}finally{r.errors=q.errors;report.views.push(r);report.errors.push(...q.errors);await q.browser.close();}}
fs.writeFileSync(path.join(root,'docs/release16-responsive.json'),JSON.stringify(report,null,2));})();
