const {open,read,click,fs,path,root}=require('./release15-qa-lib');
const out=path.join(root,'screenshots/ReleaseCandidatePolish15');fs.mkdirSync(out,{recursive:true});
(async()=>{const q=await open(),p=q.p,manifest={mode:'isolated visual fixtures; not natural progression evidence',screens:[],errors:[]};
const shot=async n=>{await p.screenshot({path:path.join(out,n+'.png')});manifest.screens.push({file:n+'.png',state:await read(p)});};
const place=async(x,y)=>{await p.evaluate(([x,y])=>{const s=scene15.__os,v=scene15.getVariables();v.get('GameState').setString('play');v.get('Hull').setNumber(3);s.x=x;s.y=y;s.vx=s.vy=0;s.inv=0;scene15.__osCam={x:Math.max(480,Math.min(5720,x)),y:Math.max(270,Math.min(2730,y))};scene15.getObjects('Ship')[0].setCenterPositionInScene(x,y);},[x,y]);await p.waitForTimeout(180);};
const region=async(id,n)=>{const r=await p.evaluate(id=>scene15.__g13.regions.find(r=>r.id===id),id);if(!r)throw Error('missing region '+id);await place(r.x-100,r.y+80);await shot(n);};
try{await shot('01-menu');await click(p,'ButtonBg');await p.evaluate(()=>scene15.__g13Generate(130013));await shot('02-first-flight');await region('working','09-working-orbit');await shot('03-loot-readability');await place(1050,760);await shot('04-loot-vs-decoration');await place(800,600);await shot('05-common-loot');let s=await read(p),l=s.loot.find(o=>o.kind==='energy');await place(l.x-130,l.y+50);await shot('06-rare-loot');
await region('debris','10-debris-field');await shot('13-route-choice');await region('graveyard','11-satellite-graveyard');await region('meteor','12-meteor-channel');await p.evaluate(()=>scene15.__g13.meteor.clock=3.7);await shot('08-meteor-warning');await p.evaluate(()=>scene15.__g13.meteor.clock=4.7);await shot('07-meteor');
await place(900,700);await p.evaluate(()=>{const v=scene15.getVariables();v.get('MissionProgress').setNumber(3);});await shot('14-mission-chain');await p.evaluate(()=>{const v=scene15.getVariables();v.get('CargoValue').setNumber(80);v.get('Cargo').setNumber(6);v.get('MissionProgress').setNumber(6);});await place(260,700);await shot('15-result');await click(p,'ResultButtonBg');await shot('16-upgrades');
await p.evaluate(()=>{const v=scene15.getVariables();v.get('CargoMax').setNumber(10);v.get('EngineLevel').setNumber(1);v.get('RadarLevel').setNumber(1);v.get('HullMax').setNumber(4);v.get('SectorUnlocked').setNumber(1);});await click(p,'UpgradeBackButtonBg');await shot('18-sector2-unlock');await click(p,'SectorSelectButtonBg',1);await p.evaluate(()=>scene15.__g13Generate(430022));await shot('19-sector2');await shot('17-upgraded-ship');await region('meteor','20-sector2-danger');s=await read(p);await place(s.signal.x-130,s.signal.y+60);await shot('21-signal');await place(s.key.x-130,s.key.y+45);await p.waitForTimeout(1500);await shot('22-key');await place(s.key.x,s.key.y);await place(s.gate.x-210,s.gate.y);await p.waitForTimeout(1500);await shot('23-gate');
for(let i=0;i<4;i++){await p.evaluate(i=>{scene15.__g13.secret={stage:4,template:i,progress:0,cache:false};},i);const model=require('./release15-secret-model')(i);await place(...model.points[Math.min(3,model.points.length-1)]);await p.waitForTimeout(1300);await shot('2'+(4+i)+'-secret-template-'+String.fromCharCode(97+i));if(i===0){await place(model.gates[1].x-45,model.gates[1].y+20);await p.evaluate(()=>scene15.__os.phase=1.1);await p.waitForTimeout(50);await shot('28-laser-double');await place(model.gates[3].x-45,model.gates[3].y+20);await p.evaluate(()=>scene15.__os.phase=4.85);await p.waitForTimeout(50);await shot('29-laser-cross');}}
const cache=require('./release15-secret-model')(3).cache;await p.evaluate(()=>scene15.__g13.secret.progress=6);await place(...cache);await shot('30-secret-reward');
await p.waitForTimeout(2500);for(let i=0;i<10;i++){await p.evaluate(i=>{scene15.getVariables().get('CurrentSector').setNumber(i<5?1:2);scene15.__g13Generate(130013+i*100003);},i);s=await read(p);await place(s.regions[1].x-120,s.regions[1].y+100);if(i<3)await shot('3'+(i+1)+'-seed-'+String.fromCharCode(97+i));else{const dir=path.join(root,'_tmp-export/release15-seed-views');fs.mkdirSync(dir,{recursive:true});await p.screenshot({path:path.join(dir,'seed-'+i+'.png')});}}
}catch(e){manifest.failure=e.stack;console.error(e);}finally{manifest.errors=q.errors;await q.browser.close();}
for(const [viewport,mobile,n]of[[{width:1280,height:720},true,'34-mobile-landscape'],[{width:720,height:1280},true,'35-mobile-portrait']]){const q=await open(viewport,mobile);try{if(viewport.width>viewport.height){await click(q.p,'ButtonBg');await q.p.touchscreen.tap(950,400);await q.p.waitForTimeout(150);}await q.p.screenshot({path:path.join(out,n+'.png')});manifest.screens.push({file:n+'.png',state:await read(q.p)});manifest.errors.push(...q.errors);}finally{await q.browser.close();}}
fs.writeFileSync(path.join(root,'docs/release15-screens.json'),JSON.stringify(manifest,null,2));})();
