module.exports=function setup17(scene){
 if(scene.__release17)return;scene.__release17=true;
 const v=scene.getVariables(),N=k=>v.get(k).getAsNumber(),S=k=>v.get(k).getAsString(),state=x=>v.get('GameState').setString(x),audio=scene.__audio16;
 const generate=scene.__g13Generate;scene.__g13Generate=seed=>{generate(seed);scene.__world17(scene.__g13,N('CurrentSector'));};
 let prefs={};try{prefs=JSON.parse(localStorage.getItem('orbitalSettings17')||'{}')}catch{}
 audio.music=prefs.ambience===true;audio.sfx=prefs.sfx!==false;audio.enabled=prefs.master??audio.enabled;
 const tone=audio.tone;audio.tone=kind=>{if(kind==='ambient'||audio.sfx)tone(kind)};
 scene.__prefs17=()=>localStorage.setItem('orbitalSettings17',JSON.stringify({master:audio.enabled,sfx:audio.sfx,ambience:audio.music}));
 const mission=scene.__osMission;
 // Keep all twenty existing missions. Introduce an early chain where the
 // player has enough range, then rotate three new chains with the old pool.
 const chains=[['relayrepair','ВОССТАНОВИТЬ МАЯК',3,130,0,0],['blackboxchain','СЛЕД ПРОПАВШЕГО СУДНА',4,175,1,0],['rescuechain','СПАСАТЕЛЬНЫЙ ПРОТОКОЛ',4,180,1,0]];
 scene.__chains17=chains;scene.__osMission=()=>{mission();const c=N('ContractsCompleted'),m=c===2?chains[0]:c>=20&&c%23>=20?chains[c%23-20]:null;if(m){for(const[k,i]of[['MissionType',0],['Mission',1]])v.get(k).setString(m[i]);for(const[k,i]of[['MissionTarget',2],['MissionReward',3],['MissionTechReward',4],['MissionTimeLimit',5]])v.get(k).setNumber(m[i]);}scene.__radio16={text:c===0?'ДИСПЕТЧЕР / Добро пожаловать на рабочую орбиту. Светлые детали — добыча. Верните шесть на станцию.':N('CurrentSector')===2?'ДИСПЕТЧЕР / В поясе пропала исследовательская экспедиция. Сканер поймал неизвестный сигнал.':c>=5?'ДИСПЕТЧЕР / Пояс обломков откроется после подготовки корабля. Условия — в выборе сектора.':'ДИСПЕТЧЕР / '+S('Mission')+'. Маршрут отмечен на навигаторе.',life:8};};
 const oldshell=scene.__shell16;scene.__shell16=dt=>{oldshell(dt);document.getElementById('orbital-tools16').style.display='none';};
 const css=document.createElement('style');css.textContent=`
 #shell17{font-family:Exo17,Arial,sans-serif;color:#dfedf2;position:fixed;inset:0;z-index:9100;pointer-events:none}#shell17 *{box-sizing:border-box}#shell17 button,#shell17 input{font:600 clamp(14px,1.3vw,20px) Exo17,Arial,sans-serif;cursor:pointer}#shell17 button{color:#deedf3;background:#173b50;border:1px solid #4d8299;border-radius:7px;padding:12px 20px;min-height:44px;transition:background .12s,border-color .12s}#shell17 button:hover{background:#285d72;border-color:#9cdef0}#shell17 button:active{transform:translateY(1px);background:#377086}#shell17 .primary{background:#267e98;border-color:#83d5e6;font-weight:700}#shell17 .subtle{background:#102637;color:#aec3ce}#shell17 .overlay{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:#030c18b8;pointer-events:auto}#shell17 .card{width:min(700px,82vw);max-height:92vh;overflow:auto;padding:clamp(22px,3.5vh,42px) clamp(25px,3.8vw,54px);border:1px solid #59879e;border-top:3px solid #77ccde;border-radius:14px;background:linear-gradient(145deg,#153348,#091c2d);box-shadow:0 24px 100px #02091699;text-align:center}#shell17 h1{font-size:clamp(28px,3vw,48px);line-height:1.15;font-weight:750;margin:12px 0 20px;letter-spacing:.02em}#shell17 h2{font-size:clamp(24px,2.4vw,34px);margin:12px 0 20px}#shell17 p{line-height:1.55;color:#b0c7d1;margin:14px 0 24px;font-size:clamp(15px,1.3vw,20px)}#shell17 .eyebrow{color:#83b6c9;letter-spacing:.19em;font-size:13px}#shell17 .actions{display:grid;gap:12px;margin-top:22px}#shell17 .row{display:flex;gap:10px;justify-content:center;flex-wrap:wrap}#shell17 .toolbar{position:absolute;right:24px;bottom:22px;display:flex;gap:8px;pointer-events:auto}#shell17 .nav{position:absolute;bottom:10%;left:50%;transform:translateX(-50%);display:flex;align-items:center;gap:14px;max-width:80vw;background:#091c2dee;border:1px solid #426479;border-radius:8px;padding:10px 18px;font-size:clamp(15px,1.35vw,22px)}#shell17 .nav small{display:block;font-size:.77em;color:#94b3c2;margin-top:4px}#shell17 .compass{display:block;width:24px;height:24px;color:#b3dfeb;font-size:25px;line-height:24px;flex-shrink:0}#shell17 .debug{pointer-events:auto;position:absolute;left:20px;top:24%;background:#091721f5;border:1px solid #b29050;border-radius:10px;padding:18px;width:340px;max-height:70vh;overflow:auto;font-size:14px}#shell17 .debug button{font-size:13px;padding:8px;min-height:34px}#shell17 .debug pre{white-space:pre-wrap;color:#b6cbd4}#shell17 .debug .actions{grid-template-columns:1fr 1fr;gap:7px;margin:12px 0}#shell17 .journal{font-size:16px;text-align:left;padding:14px;background:#091b29;border-radius:8px;line-height:1.65}#shell17 .settings-row{display:flex;justify-content:space-between;align-items:center;margin:18px 0;gap:15px}
 `;document.head.appendChild(css);
 // Font already exists in the project under OFL. No runtime CDN request.
 const f=new FontFace('Exo17','url(Exo2-Variable.ttf)',{weight:'100 900'});f.load().then(x=>document.fonts.add(x)).catch(()=>{});
 const root=document.createElement('div');root.id='shell17';document.body.appendChild(root);
 const debugCanvas=document.createElement('canvas');debugCanvas.style.cssText='position:absolute;inset:0;pointer-events:none';root.appendChild(debugCanvas);
 root.addEventListener('pointerdown',e=>{if(e.target.closest('button,input,.overlay,.debug')){e.stopPropagation();if(scene.__osPointer){scene.__osPointer.active=false;scene.__osPointer.down=false;}}});root.addEventListener('pointerup',e=>e.stopPropagation());
 const overlay=document.createElement('div'),toolbar=document.createElement('div'),nav=document.createElement('div'),debug=document.createElement('div');overlay.className='overlay';toolbar.className='toolbar';nav.className='nav';debug.className='debug';root.append(overlay,toolbar,nav,debug);
 nav.innerHTML='<span class="compass">➜</span><div><span class="destination"></span><small></small></div>';
 const devAllowed=['localhost','127.0.0.1','[::1]'].includes(location.hostname)||new URLSearchParams(location.search).get('dev')==='1';
 const shell={page:'',devOpen:false,journal:false,returnState:'menu',confirm:null,devAllowed,nav,root,overlay,toolbar,debug,debugCanvas};scene.__ui17=shell;
 const button=(parent,label,fn,style='')=>{const b=document.createElement('button');b.textContent=label;b.className=style;b.onclick=e=>{e.stopPropagation();audio.unlock();audio.tone('click');fn();};parent.appendChild(b);return b;};
 const resume=()=>{state(shell.returnState==='play'?'play':'menu');shell.page='';};
 const abandon=(fn)=>{if(shell.returnState==='play'&&(N('Cargo')>0||scene.__g13?.secret.stage>0)){shell.confirm=fn;state('confirm17');}else fn();};
 const start=()=>{shell.page='';scene.__start17();};
 shell.pause=()=>{if(S('GameState')==='play'){shell.returnState='play';state('pause17');}else if(S('GameState')==='pause17')resume();};
 shell.arcade=()=>{shell.arcadeReturn=S('GameState')==='pause17'?'pause17':'menu';state('arcade');scene.__arcade16.start();};
 shell.exitArcade=()=>{scene.__arcade16.active=false;state(shell.arcadeReturn||'menu');};
 window.addEventListener('keydown',e=>{if(e.code==='Escape'){const st=S('GameState');if(['play','pause17','settings17','journal17','confirm17','arcade'].includes(st)){e.preventDefault();e.stopImmediatePropagation();if(st==='arcade')shell.exitArcade();else if(st==='play'||st==='pause17')shell.pause();else state(shell.returnState==='play'?'pause17':'menu');}}if(e.code==='KeyJ'&&S('GameState')==='play'){shell.returnState='play';state('journal17');}},true);
 const skip=button(toolbar,'ПРОПУСТИТЬ СООБЩЕНИЕ',()=>{if(scene.__radio16)scene.__radio16.life=0;},'subtle'),pause=button(toolbar,'Ⅱ ПАУЗА',shell.pause),journal=button(toolbar,'ЖУРНАЛ',()=>{shell.returnState='play';state('journal17');}),back=button(toolbar,'ВЫЙТИ ИЗ ПАТРУЛЯ',shell.exitArcade);const dev=button(toolbar,'DEV',()=>{shell.devOpen=!shell.devOpen;scene.__os.dev=shell.devOpen;});skip.style.fontSize='12px';
 shell.render=()=>{
  const st=S('GameState'),portrait=innerHeight>innerWidth*1.08;root.style.display=portrait?'none':'';pause.hidden=st!=='play';journal.hidden=st!=='play';back.hidden=st!=='arcade';dev.hidden=!devAllowed;toolbar.style.display=portrait?'none':'flex';debugCanvas.style.display=devAllowed&&shell.devOpen&&st==='play'&&(shell.poi||shell.hazards)?'block':'none';
  skip.hidden=st!=='play'||!(scene.__radio16?.life>0);
  const pages=['menu','pause17','settings17','journal17','confirm17'];overlay.style.display=pages.includes(st)?'flex':'none';nav.style.display=st==='play'?'flex':'none';debug.style.display=devAllowed&&shell.devOpen?'block':'none';
  if(shell.page!==st){shell.page=st;overlay.replaceChildren();if(pages.includes(st)){const card=document.createElement('section');card.className='card';overlay.appendChild(card);const headline=document.createElement('h1'),desc=document.createElement('p'),actions=document.createElement('div');actions.className='actions';card.innerHTML='<div class="eyebrow">ORBITAL SALVAGE · СЛУЖБА СБОРА</div>';card.append(headline,desc,actions);
   if(st==='menu'){headline.textContent='КОСМИЧЕСКИЙ СБОРЩИК';desc.textContent='Исследуйте потерянную орбиту. Находите ценный груз, выполняйте контракты и возвращайтесь домой.';button(actions,N('RunCount')?'ПРОДОЛЖИТЬ — НОВЫЙ ВЫЛЕТ':'НАЧАТЬ ВЫЛЕТ',start,'primary');button(actions,'ВЫБОР СЕКТОРА',()=>state('sectorSelect'),'subtle');button(actions,'ОРБИТАЛЬНЫЙ ПАТРУЛЬ',shell.arcade,'subtle');button(actions,'НАСТРОЙКИ',()=>{shell.returnState='menu';state('settings17');},'subtle');}
   if(st==='pause17'){headline.textContent='ПАУЗА';desc.textContent='Полёт остановлен. Ваш груз и маршрут сохранены до продолжения.';button(actions,'ПРОДОЛЖИТЬ',resume,'primary');button(actions,'ПЕРЕЗАПУСТИТЬ ВЫЛЕТ',()=>abandon(start),'subtle');button(actions,'ВЫБОР СЕКТОРА',()=>abandon(()=>state('sectorSelect')),'subtle');button(actions,'ОРБИТАЛЬНЫЙ ПАТРУЛЬ',shell.arcade,'subtle');button(actions,'НАСТРОЙКИ',()=>state('settings17'),'subtle');button(actions,'В ГЛАВНОЕ МЕНЮ',()=>abandon(()=>state('menu')),'subtle');}
   if(st==='settings17'){headline.textContent='НАСТРОЙКИ';desc.textContent='Звук включается после первого нажатия. Настройки сохраняются на устройстве.';for(const [label,key]of[['ОБЩИЙ ЗВУК','enabled'],['ЭФФЕКТЫ','sfx'],['АМБИЕНТ','music']]){const row=document.createElement('div');row.className='settings-row';row.textContent=label;actions.appendChild(row);const b=button(row,audio[key]?'ВКЛ':'ВЫКЛ',()=>{audio[key]=!audio[key];b.textContent=audio[key]?'ВКЛ':'ВЫКЛ';scene.__prefs17();});}button(actions,'НАЗАД',()=>state(shell.returnState==='play'?'pause17':'menu'));}
   if(st==='confirm17'){headline.textContent='ЗАВЕРШИТЬ ТЕКУЩИЙ ВЫЛЕТ?';desc.textContent='Недоставленный груз и текущий секретный маршрут будут потеряны. Купленные модули и кредиты сохранятся.';button(actions,'ОТМЕНА',()=>state('pause17'),'primary');button(actions,'ЗАВЕРШИТЬ',()=>{const fn=shell.confirm;shell.confirm=null;fn?.();},'subtle');}
   if(st==='journal17'){headline.textContent='БОРТОВОЙ ЖУРНАЛ';desc.textContent='Контракт: '+S('Mission');const note=document.createElement('div');note.className='journal';const g=scene.__g13;note.textContent=N('CurrentSector')===2?'Потерянная экспедиция: '+(g.secret.stage===0?'найдите неизвестный сигнал — направление показывает отдельная кнопка навигации.':g.secret.stage===1?'восстановите ключ доступа.':g.secret.stage<4?'вернитесь к исследовательскому шлюзу.':g.secret.cache?'архив получен. Возвращайтесь на станцию.':'пройдите шесть контрольных точек и заберите архив.'):'Для пояса обломков: 6 контрактов, 2 установленных модуля и оборот 1800 кредитов. Сейчас '+N('ContractsCompleted')+'/6; модули '+scene.__osInstalledCount()+'/2; оборот '+(N('Credits')+N('SpentCredits'))+'/1800.';actions.appendChild(note);button(actions,'КОНТРАКТ',()=>{shell.tracked='contract';state('play');},'primary');if(N('CurrentSector')===2&&g.secret.stage<4)button(actions,'ОТСЛЕЖИВАТЬ НЕИЗВЕСТНЫЙ СИГНАЛ',()=>{shell.tracked='secret';state('play');});button(actions,'ВОЗВРАЩЕНИЕ НА СТАНЦИЮ',()=>{shell.tracked='station';state('play');});button(actions,'ПРОДОЛЖИТЬ',()=>state('play'));}
  }}
 };
 // Buttons call the same generation/start/mission/reward methods as gameplay.
 debug.innerHTML='<b>DEV · ИЗОЛИРОВАННЫЕ ПРОВЕРКИ</b><pre></pre>';const da=document.createElement('div');da.className='actions';debug.appendChild(da);
 const devStart=sector=>{v.get('CurrentSector').setNumber(sector);start();scene.__os.dev=true;};
 for(const[label,fn]of[
 ['НОВЫЙ SEED',()=>scene.__g13Generate()],['СЕКТОР 1',()=>devStart(1)],['СЕКТОР 2',()=>devStart(2)],
 ['СЕКРЕТ',()=>{devStart(2);scene.__g13Generate();scene.__g13.secret.stage=4;scene.__g13.secret.progress=0;Object.assign(scene.__os,{x:4610,y:2170,vx:0,vy:0});scene.getObjects('Ship')[0].setCenterPositionInScene(4610,2170);scene.__osCam={x:4610,y:2170};}],
 ['МЕТЕОРНЫЙ ПОТОК',()=>{const r=scene.__g13.regions.find(r=>r.id==='meteor');Object.assign(scene.__os,{x:r.x-300,y:r.y+310,vx:0,vy:0});scene.getObjects('Ship')[0].setCenterPositionInScene(scene.__os.x,scene.__os.y);scene.__osCam={x:scene.__os.x,y:scene.__os.y};scene.__g13.meteor.clock=4.1;shell.tracked='meteor';state('play');scene.__radio16={text:'ДИСПЕТЧЕР / Испытательное окно метеорного потока. Войдите через просвет.',life:5};}],
 ['ПОГОНЯ',()=>{const g=scene.__g13;g.chase16.phase='warning';g.chase16.time=2.5;g.chase16.region=g.region;state('play');}],
 ['СЛЕДУЮЩИЙ КОНТРАКТ',()=>{shell.contractIndex=((shell.contractIndex??N('ContractsCompleted'))+1)%23;const old=N('ContractsCompleted');v.get('ContractsCompleted').setNumber(shell.contractIndex);scene.__osMission();v.get('ContractsCompleted').setNumber(old);v.get('MissionProgress').setNumber(0);scene.__g13.chain17=null;shell.tracked='contract';}],
 ['+500 КРЕДИТОВ',()=>v.get('Credits').setNumber(N('Credits')+500)],['+1 ТЕХНОДЕТАЛЬ',()=>v.get('TechParts').setNumber(N('TechParts')+1)],
 ['СБРОС СОХРАНЕНИЯ',()=>{if(confirm('Удалить только прогресс Orbital Salvage на этом адресе?')){localStorage.removeItem('orbitalSalvageSave');location.reload();}}],
 ['ПОКАЗАТЬ POI',()=>shell.poi=!shell.poi],['ПОКАЗАТЬ ОПАСНОСТИ',()=>shell.hazards=!shell.hazards],['ПОВТОРИТЬ SEED',()=>scene.__g13Generate(scene.__g13.seed)],['УЛУЧШЕНИЯ',()=>state('upgrades')]
 ])button(da,label,()=>{if(devAllowed)fn();});
};
