const fs=require('fs'),assert=require('assert/strict'),cp=require('child_process');
const load=n=>JSON.parse(fs.readFileSync('docs/world20-'+n+'.json'));
const seeds=load('seeds'),natural=load('natural-final'),mobile=load('mobile-flow'),regression=load('regression'),visual=load('visual-qa'),perf=load('perf-isolation'),ads=load('ads'),save=load('save'),exp=load('export-qa'),views=load('final-views');
for(const [name,r]of Object.entries({seeds,natural,mobile,regression,visual,perf,ads,save,exp,views})){assert.ok(!r.failure,name);assert.equal(r.errors?.length||0,0,name);}
assert.equal(seeds.seeds.length,100);assert.equal(visual.flights.length,5);assert.equal(natural.events.find(e=>e.name==='secret-end').state.secret.cache,true);assert.ok(natural.events.some(e=>e.name==='reload-continue'));assert.equal(perf.data.finalState,'play');assert.ok(perf.segments.every(s=>s.state==='play'));assert.deepEqual(perf.data.instances,[869,869]);
const audit=JSON.parse(cp.execFileSync(process.execPath,['scripts/audit-project.js'],{encoding:'utf8'}));
const r={base:'533cda8f222755a8e75a69f484a6beaef2fd13f7',library:{large:16,medium:24,small:30,newBackground:0},structuralSeeds:seeds.seeds.map(s=>s.seed),visualSeeds:Array.from({length:15},(_,i)=>130013+i*100019),keyboardFixtureSeeds:visual.flights.map(f=>f.seed),natural:{method:natural.mode,seconds:natural.events.find(e=>e.name==='reload-continue').seconds,cache:true,errors:natural.errors},performance:perf.data,tracedPerformance:load('performance-summary'),mobile,staticAudit:audit,externalAnalytics:regression.externalAnalytics,screenshots:fs.readdirSync('screenshots/WorldArtGeneration20').filter(n=>n.endsWith('.png')),remaining:['Physical device / production Yandex wrapper and ads not tested','Trace-heavy QA spikes documented; not represented as zero runtime spikes'],verdict:'READY FOR FINAL RELEASE QA'};
if(perf.data.max>100||perf.data.p95>20){r.verdict='NOT READY';r.remaining.push('Final benchmark still contains significant frame spikes; performance acceptance not closed');}
fs.writeFileSync('docs/world20-summary.json',JSON.stringify(r,null,2));console.log({verdict:r.verdict,screenshots:r.screenshots.length,audit});
